/** Bilingual titles for every EGB339 vault entry, generated from en.json/nb.json. */
export const EGB339_TITLES: Record<string, { no: string; en: string }> = {
  "uke-1": { no: "Introduksjon til robotikk", en: "Unit Introduction and Kinematics Context" },
  "uke-2": { no: "Lineær algebra og 2D-pose", en: "Linear Algebra and 2D Pose" },
  "uke-3": { no: "NumPy og 3D-pose", en: "NumPy and 3D Pose" },
  "uke-4": { no: "Forward kinematics", en: "Forward Kinematics" },
  "uke-5": { no: "Inverse kinematics", en: "Inverse Kinematics" },
  "uke-6": { no: "Robot Jacobian", en: "Robot Jacobian" },
  "uke-7": { no: "Bevegelsesplanlegging", en: "Motion Planning" },
  "uke-8": { no: "Bilder og bildebehandling", en: "Images and Image Processing" },
  "atan2-and-inverse-trigonometry": { no: "atan2 og invers trigonometri", en: "atan2 and inverse trigonometry" },
  "colour-normalization-and-chromaticity": { no: "Fargenormalisering og kromatisitet", en: "Colour normalization and chromaticity" },
  "coppeliasim": { no: "CoppeliaSim", en: "CoppeliaSim" },
  "differential-kinematics-and-local-linearisation": { no: "Differensiell kinematikk og lokal linearisering", en: "Differential kinematics and local linearisation" },
  "digital-image-representation": { no: "Digital bilderepresentasjon", en: "Digital image representation" },
  "dobot-magician": { no: "Dobot Magician", en: "Dobot Magician" },
  "egb339-weeks-1-6-robotics-foundations": { no: "EGB339 uke 1–6 – Robotikkgrunnlag", en: "EGB339 Weeks 1-6 - Robotics foundations" },
  "egb339-weeks-1-8-robotics-and-vision-foundations": { no: "EGB339 uke 1–8 – Robotikk- og visiongrunnlag", en: "EGB339 Weeks 1-8 - Robotics and vision foundations" },
  "egb339-weeks-1-5-robotics-foundations": { no: "EGB339 uke 1–5 – Robotikkgrunnlag", en: "EGB339 Weeks 1–5 – Robotics foundations" },
  "forward-kinematics": { no: "Forward kinematics", en: "Forward kinematics" },
  "image-histograms-and-thresholding": { no: "Bildehistogrammer og terskling", en: "Image histograms and thresholding" },
  "image-representation-and-processing": { no: "Bilderepresentasjon og -behandling", en: "Image representation and processing" },
  "inverse-kinematics": { no: "Inverse kinematics", en: "Inverse kinematics" },
  "joint-angle-mapping": { no: "Leddvinkel-mapping", en: "Joint-angle mapping" },
  "keyboard-coordinate-mapping-and-safe-key-presses": { no: "Tastaturkoordinater og sikre tastetrykk", en: "Keyboard coordinate mapping and safe key presses" },
  "kinematic-chains-and-joints": { no: "Kinematiske kjeder og ledd", en: "Kinematic chains and joints" },
  "linear-algebra-for-robotics": { no: "Lineær algebra for robotikk", en: "Linear algebra for robotics" },
  "monadic-and-dyadic-image-operations": { no: "Monadiske og dyadiske bildeoperasjoner", en: "Monadic and dyadic image operations" },
  "numpy-arrays-and-matrix-operations": { no: "NumPy-arrayer og matriseoperasjoner", en: "NumPy arrays and matrix operations" },
  "optimization-based-inverse-kinematics": { no: "Optimaliseringsbasert inverse kinematics", en: "Optimization-based inverse kinematics" },
  "partial-derivatives-for-robotics": { no: "Partiellderiverte for robotikk", en: "Partial derivatives for robotics" },
  "planar-homographies": { no: "Plane homografier", en: "Planar homographies" },
  "point-to-segment-distance-and-obstacle-clearance": { no: "Punkt–segment-avstand og hindringsklaring", en: "Point-to-segment distance and obstacle clearance" },
  "pose-graphs": { no: "Posegrafer", en: "Pose graphs" },
  "position-orientation-and-robot-kinematics": { no: "Posisjon, orientering og robotkinematikk", en: "Position, orientation and robot kinematics" },
  "public-and-private-autograder-tests": { no: "Offentlige og private autograder-tester", en: "Public and private autograder tests" },
  "python-control-flow-and-collections": { no: "Python kontrollflyt og samlinger", en: "Python control flow and collections" },
  "reference-frames": { no: "Referanserammer", en: "Reference frames" },
  "robot-jacobian": { no: "Robot-Jacobian", en: "Robot Jacobian" },
  "robot-motion-interpolation": { no: "Interpolasjon av robotbevegelse", en: "Robot motion interpolation" },
  "robot-workspace-and-ik-solution-branches": { no: "Robotarbeidsrom og IK-løsningsgrener", en: "Robot workspace and IK solution branches" },
  "rotation-composition-in-3d": { no: "Rotasjonskomposisjon i 3D", en: "Rotation composition in 3D" },
  "se-2-homogeneous-transformations": { no: "SE(2) homogene transformasjoner", en: "SE(2) homogeneous transformations" },
  "se-3-homogeneous-transformations": { no: "SE(3) homogene transformasjoner", en: "SE(3) homogeneous transformations" },
  "shape-descriptors-from-area-and-perimeter": { no: "Formbeskrivelser fra areal og omkrets", en: "Shape descriptors from area and perimeter" },
  "so-2-rotation-matrices": { no: "SO(2) rotasjonsmatriser", en: "SO(2) rotation matrices" },
  "so-3-rotation-matrices": { no: "SO(3) rotasjonsmatriser", en: "SO(3) rotation matrices" },
  "trapezoidal-motion-profiles": { no: "Trapesformede hastighetsprofiler", en: "Trapezoidal motion profiles" },
  "assessment-1-problem-solving-task-overview": { no: "Assessment 1 – Oversikt over problem-solving-oppgaven", en: "Assessment 1 - Problem-solving task overview" },
  "assessment-1-0-warmup-to-gradescope": { no: "Assessment 1.0 – Oppvarming til Gradescope", en: "Assessment 1.0 - Warmup to Gradescope" },
  "assessment-1-1-position-and-orientation-in-2d": { no: "Assessment 1.1 – Posisjon og orientering i 2D", en: "Assessment 1.1 - Position and orientation in 2D" },
  "assessment-1-2-position-and-orientation-in-3d": { no: "Assessment 1.2 – Posisjon og orientering i 3D", en: "Assessment 1.2 – Position and orientation in 3D" },
  "assessment-1-3-dobot-forward-kinematics": { no: "Assessment 1.3 – Dobot forward kinematics", en: "Assessment 1.3 – Dobot forward kinematics" },
  "assessment-1-4-robot-inverse-kinematics": { no: "Assessment 1.4 – Robot inverse kinematics", en: "Assessment 1.4 - Robot inverse kinematics" },
  "assessment-1-5-warehouse-automation": { no: "Assessment 1.5 – Lagerautomatisering", en: "Assessment 1.5 - Warehouse automation" },
  "assessment-1-6-vision-fundamentals-part-1": { no: "Assessment 1.6 – Vision-grunnlag del 1", en: "Assessment 1.6 - Vision fundamentals part 1" },
  "assessment-1-7-vision-fundamentals-part-2": { no: "Assessment 1.7 – Vision-grunnlag del 2", en: "Assessment 1.7 - Vision fundamentals part 2" },
  "assessment-2-applied-project-overview": { no: "Assessment 2 – Oversikt over det anvendte prosjektet", en: "Assessment 2 - Applied project overview" },
  "assessment-2-1-simulation-and-oral-demonstration": { no: "Assessment 2.1 – Simulering og muntlig demonstrasjon", en: "Assessment 2.1 - Simulation and oral demonstration" },
  "assessment-2-2-physical-robot-submission": { no: "Assessment 2.2 – Fysisk robot-innlevering", en: "Assessment 2.2 - Physical robot submission" },
  "coppeliasim-forward-kinematics-practical": { no: "CoppeliaSim forward kinematics practical", en: "CoppeliaSim forward kinematics practical" },
  "coppeliasim-setup": { no: "CoppeliaSim-oppsett", en: "CoppeliaSim setup" },
  "egb339-course-and-assessment-overview": { no: "EGB339 emne- og vurderingsoversikt", en: "EGB339 course and assessment overview" },
  "robot-word-typing-practical": { no: "Robot ordskriving practical", en: "Robot word typing practical" },
};

export function egb339Title(slug: string, lang: "no" | "en"): string | null {
  const entry = EGB339_TITLES[slug];
  return entry ? entry[lang] : null;
}
