import type { Egb339Problem } from "./egb339-problems";
import type { Egb339ProblemEn } from "./egb339-problems-en";

type Bilingual = { title: string; prompt: string; solution: string; answer: string };
type VisionCard = {
  id: string; source: string; sourcePage: number; verification: Egb339Problem["verification"];
  topics: Egb339Problem["topics"]; no: Bilingual; en: Bilingual;
};
const link = (label: string, slug: string) => ({ label, href: `/egb339/temaer/${slug}` });
const filter = link("Romlige filtre", "spatial-filtering-and-convolution");
const regions = link("Regioner og momenter", "connected-components-and-image-moments");
const morphology = link("Binær morfologi", "binary-morphology");
const shape = link("Formmål", "shape-descriptors-from-area-and-perimeter");
const colour = link("Fargesegmentering", "colour-spaces-and-colour-segmentation");
const homography = link("Plane homografier", "planar-homographies");
const camera = link("Hullkamera", "pinhole-camera-model-and-camera-parameters");
const calibration = link("Kalibrering og warping", "calibration-markers-and-image-warping");
const optics = link("Linser og dybdeskarphet", "lens-aperture-and-depth-of-field");

const week9: VisionCard[] = [
  {
    id: "w9-tutorial-regions", source: "Week 9 Tutorial - Feature Extraction and Spatial Operators", sourcePage: 4,
    verification: "official", topics: [regions, shape],
    no: { title: "Tutorial 1: fem regioner og tyngdepunkter", prompt: "Identifiser de fem sammenhengende hvite regionene i QUTs 15 × 15-rutenett (tutorial s. 4). Finn areal og tyngdepunkt per region i $(u,v)$-koordinater.", solution: "### Fra piksler til momenter\n\n1. Bruk hvit som forgrunn og merk hver region; bakgrunn får etikett 0.\n2. Tell piksler: $m_{00}=\\sum I$. Summer kolonner $m_{10}=\\sum uI$ og rader $m_{01}=\\sum vI$.\n3. Del: $(\\bar u,\\bar v)=(m_{10}/m_{00},m_{01}/m_{00})$. For region 2 er $m_{00}=11$, $m_{10}=29$ og $m_{01}=79$, altså $(29/11,79/11)$.\n\nKontroller alle fem mot utdelt fasit s. 1. Kilden bruker $(u,v)$, mens array-indekser er [v,u].", answer: "Fem sentroider: $(1.5,2.5)$, $(29/11,79/11)$, $(7,11)$, $(12.5,8.5)$ og $(11.5,4.5)$." },
    en: { title: "Tutorial 1: five regions and centroids", prompt: "Identify five connected white regions in the 15 × 15 grid on QUT tutorial p. 4. Calculate area and centroid in $(u,v)$ coordinates.", solution: "### From pixels to moments\n\n1. Treat white as foreground; label connected regions and use label 0 for background.\n2. Count pixels $m_{00}=\\sum I$, sum columns $m_{10}=\\sum uI$ and rows $m_{01}=\\sum vI$.\n3. Divide: $(\\bar u,\\bar v)=(m_{10}/m_{00},m_{01}/m_{00})$. For region 2, $m_{00}=11$, $m_{10}=29$, $m_{01}=79$, giving $(29/11,79/11)$.\n\nCheck all five against the supplied solutions p. 1. Coordinates are $(u,v)$; array indices are [v,u].", answer: "Five centroids: $(1.5,2.5)$, $(29/11,79/11)$, $(7,11)$, $(12.5,8.5)$ and $(11.5,4.5)$." },
  },
  {
    id: "w9-tutorial-mean", source: "Week 9 Tutorial - Feature Extraction and Spatial Operators", sourcePage: 7,
    verification: "corrected", topics: [filter],
    no: { title: "Tutorial 2: 3 × 3-middelfilter og fasitavvik", prompt: "Et 6 × 6-bilde har verdi 0,1 bortsett fra 0,8 ved $(2,2)$ og $(4,4)$. Bruk sentrert $3\\times3$-middel og dupliser kantpikslene. Beregn én, to og hjørneuteliggere.", solution: "### Vektet sum, ikke median\n\nKjernen har ni like vekter $1/9$. Ett lyst punkt gir $[8(0.1)+0.8]/9=8/45\\approx0.1778$; to lyse gir $[7(0.1)+2(0.8)]/9=23/90\\approx0.2556$. Dupliser nærmeste kantverdi utenfor bildet, og les fra originalen.\n\nNederste høyre vindu inneholder én 0,8 og åtte 0,1, også etter kantduplisering. Dermed $8/45\\approx0.1778$, eller 0,2 avrundet. QUT-fasiten s. 2 viser **0,3** her: et kildeavvik, ikke en verdi å kopiere.", answer: "Én: $8/45\\approx0.1778$; to: $23/90\\approx0.2556$. Hjørnet: $8/45\\approx0.1778$ (0,2), ikke fasitens 0,3." },
    en: { title: "Tutorial 2: 3 × 3 mean filter and source discrepancy", prompt: "A 6 × 6 image is 0.1 except for 0.8 at $(2,2)$ and $(4,4)$. Apply a centred $3\\times3$ mean with edge replication. Find one, two and corner responses.", solution: "### Weighted sum, not a median\n\nNine weights $1/9$ give $[8(0.1)+0.8]/9=8/45\\approx0.1778$ for one outlier and $[7(0.1)+2(0.8)]/9=23/90\\approx0.2556$ for two. Replicate the nearest edge value outside the image, reading from the original.\n\nThe bottom-right window still has one 0.8 and eight 0.1 values: $8/45\\approx0.1778$, or 0.2 to one decimal. The QUT answer on p. 2 prints **0.3** there; this is a source discrepancy.", answer: "One: $8/45\\approx0.1778$; two: $23/90\\approx0.2556$. Corner: $8/45\\approx0.1778$ (0.2), not the supplied 0.3." },
  },
  {
    id: "w9-tutorial-median", source: "Week 9 Tutorial - Feature Extraction and Spatial Operators", sourcePage: 7,
    verification: "official", topics: [filter],
    no: { title: "Tutorial 3: medianfilter på støybildet", prompt: "Bruk et sentrert $3\\times3$-medianfilter på det samme 6 × 6-bildet. Hva skjer med de to 0,8-pikslene og randpikslene?", solution: "### Sorter nabolaget\n\n1. Dupliser kanten som angitt.\n2. Sorter ni verdier per utpunkt og velg den femte. Høyst to er 0,8; minst sju er 0,1.\n3. Den femte er dermed 0,1 **overalt**, også ved kanten. Medianen er ikke lineær konvolusjon.", answer: "Hele utbildet er 0,1; begge isolerte 0,8-pikslene forsvinner." },
    en: { title: "Tutorial 3: median filter on noisy pixels", prompt: "Apply a centred $3\\times3$ median filter to the same 6 × 6 image. What happens to the two 0.8 pixels and boundary pixels?", solution: "### Sort the neighbourhood\n\n1. Replicate boundary values as specified.\n2. Sort nine values per output and choose the fifth. At most two are 0.8; at least seven are 0.1.\n3. The fifth is therefore 0.1 **everywhere**, including edges. A median is not linear convolution.", answer: "Every output pixel is 0.1; both isolated 0.8 pixels disappear." },
  },
  ...(["erosion", "dilation", "closing", "opening"] as const).map((operation, index): VisionCard => {
    const detail = {
      erosion: { name: "Erosjon", english: "Erosion", verb: "alle ni", verbEn: "all nine", result: 18, order: "Eroder originalen én gang.", orderEn: "Erode the original once." },
      dilation: { name: "Dilatasjon", english: "Dilation", verb: "minst én", verbEn: "at least one", result: 173, order: "Dilater originalen én gang.", orderEn: "Dilate the original once." },
      closing: { name: "Lukking", english: "Closing", verb: "minst én, deretter alle ni", verbEn: "at least one, then all nine", result: 123, order: "Dilater først hele originalen, eroder deretter det komplette mellomresultatet.", orderEn: "Dilate the entire original, then erode the complete intermediate result." },
      opening: { name: "Åpning", english: "Opening", verb: "alle ni, deretter minst én", verbEn: "all nine, then at least one", result: 58, order: "Eroder først hele originalen, dilater deretter det komplette mellomresultatet.", orderEn: "Erode the entire original, then dilate the complete intermediate result." },
    }[operation];
    return {
      id: `w9-tutorial-${operation}`, source: "Week 9 Tutorial - Feature Extraction and Spatial Operators", sourcePage: 10,
      verification: "official", topics: [morphology],
      no: { title: `Tutorial ${index + 4}: ${detail.name} av 15 × 15-masken`, prompt: `Utfør ${detail.name.toLowerCase()} på den binære 15 × 15-masken fra QUT tutorial s. 10 med en full sentrert $3\\times3$-kjerne og kantduplisering. Forklar hvert steg og antall hvite piksler.`, solution: `### Utfør operatoren\n\n1. Hvit er forgrunn. En erosjon setter sentrum til 1 hvis **alle ni** nabolagsverdier er 1; en dilatasjon gjør det hvis **minst én** er 1.\n2. ${detail.order} Dupliser nærmeste kantpiksel ved hver operasjon. Les aldri allerede endrede verdier fra samme pass.\n3. QUTs 15 × 15-resultat har **${detail.result}** hvite piksler (fasit s. ${index + 3}); dette er en kontrollsum, ikke erstatning for å tegne hele resultatmasken. Dette trinnet krever ${detail.verb} for å bli hvitt.`, answer: `${detail.name}: ${detail.result} hvite piksler med QUTs maske og kantduplisering.` },
      en: { title: `Tutorial ${index + 4}: ${detail.english} on a 15 × 15 mask`, prompt: `Apply ${detail.english.toLowerCase()} to the QUT tutorial p. 10 binary 15 × 15 mask with a full centred $3\\times3$ kernel and edge replication. Explain each pass and the white-pixel count.`, solution: `### Apply the operation\n\n1. White is foreground. Erosion sets the centre to 1 if **all nine** neighbours are 1; dilation requires **at least one**.\n2. ${detail.orderEn} Replicate the nearest boundary pixel at every pass. Do not read already modified pixels from the same pass.\n3. The QUT 15 × 15 result has **${detail.result}** white pixels (answer key p. ${index + 3}); this checksum does not replace drawing the complete mask. This step requires ${detail.verbEn} to make a pixel white.`, answer: `${detail.english}: ${detail.result} white pixels using QUT's mask and edge replication.` },
    };
  }),
  ...[
    { id: "red-blobs", n: 1, title: "Finn røde blobs", titleEn: "Find red blobs", q: "Finn separate røde regioner i red_mask.jpg.", qEn: "Identify separate red regions in red_mask.jpg.", why: "Begynn med en boolsk hvit-forgrunnsmaske, etiketter sammenhengende piksler og inspiser områdene før du klassifiserer form.", whyEn: "Start with a Boolean white-foreground mask, label connected pixels and inspect regions before classifying shape.", answer: "Tre store røde regioner er observert ved gråverdi >127, 8-naboer og areal >10000; dette er kontroll av vedlagt bilde, ikke universell fasit.", answerEn: "Three large red regions were observed with grayscale >127, 8-connectivity and area >10000; this checks the supplied image, not a universal answer.", topics: [regions] },
    { id: "circularity", n: 2, title: "Mål sirkularitet", titleEn: "Measure circularity", q: "Klassifiser de røde blob-formene med areal og omkrets.", qEn: "Classify red blob shapes using area and perimeter.", why: "Regn $\\rho=4\\pi A/P^2$ når $P>0$. Ideal sirkel gir 1, kvadrat $\\pi/4$, likesidet trekant $\\pi\\sqrt3/9$. Målte rasterkonturer avviker; velg toleranser etter inspeksjon.", whyEn: "Compute $\\rho=4\\pi A/P^2$ for $P>0$. An ideal circle gives 1, a square $\\pi/4$, an equilateral triangle $\\pi\\sqrt3/9$. Raster contours differ; set tolerances after inspecting them.", answer: "Bruk $\\rho=4\\pi A/P^2$ med dokumentert kontur- og toleransevalg; ikke krev nøyaktig idealverdi.", answerEn: "Use $\\rho=4\\pi A/P^2$ with a documented contour and tolerance rule; do not demand an exact ideal value.", topics: [shape, regions] },
    { id: "centroids-boxes", n: 3, title: "Marker tyngdepunkt og boks", titleEn: "Draw centroids and boxes", q: "Tegn sentroid og omsluttende boks for hver rød blob.", qEn: "Draw a centroid and bounding box for every red blob.", why: "Bruk $m_{10}/m_{00}$ og $m_{01}/m_{00}$ for $(u,v)$. Finn min/maks av kolonne/rad per blob, tegn på det opprinnelige bildets koordinatsystem og sjekk at etiketten ligger inne i riktig figur.", whyEn: "Use $m_{10}/m_{00}$ and $m_{01}/m_{00}$ for $(u,v)$. Take per-blob column/row bounds, draw in the original image frame and check that each label falls within its shape.", answer: "Én kontrollert sentroid og bounding box per stor rød blob; tallene avhenger av masketerskel og konturvalg.", answerEn: "One verified centroid and bounding box per large red blob; numbers depend on threshold and contour convention.", topics: [regions] },
    { id: "green-cleanup", n: 4, title: "Rydd den grønne masken", titleEn: "Clean the green mask", q: "Finn grønne blobs og velg en passende morfologisk opprydding.", qEn: "Find green blobs and choose an appropriate morphological cleanup.", why: "Sammenlign maske før/etter: åpning tar små hvite flekker, lukking fyller små svarte hull. Velg strukturelement mindre enn ønskede detaljer; beregn komponenter og mål på nytt etterpå.", whyEn: "Compare masks before/after: opening removes small white flecks, closing fills small black holes. Choose a structuring element smaller than real details; remeasure components afterwards.", answer: "To store grønne regioner i vedlagte maske ved illustrerende terskel; dokumenter valgt opprydding og eventuelle endrede arealer.", answerEn: "Two large green regions in the supplied mask under an illustrative threshold; document cleanup and changed areas.", topics: [morphology, regions] },
    { id: "blue-noise", n: 5, title: "Filtrer blå artefakter", titleEn: "Filter blue artefacts", q: "Skill ønskede blå objekter fra små og kantberørende falske blobs.", qEn: "Separate intended blue objects from small or border-touching false blobs.", why: "Sorter komponenter etter areal og egenskaper; sjekk rammeberøring, farge/maske og form. Ikke ødelegg ekte små former med en for stor morfologikjerne.", whyEn: "Rank components by area and shape, check border contact and mask quality. Do not erase real small shapes using an oversized morphology kernel.", answer: "To store blå former er observert i det vedlagte bildet; hjørneartefakter krever en begrunnet filtreringsregel.", answerEn: "Two large blue shapes were observed in the supplied image; corner artefacts require an explained filtering rule.", topics: [morphology, regions] },
    { id: "combined-records", n: 6, title: "Samle farge og formegenskaper", titleEn: "Combine colour and shape records", q: "Bygg én samling som bevarer farge, lokal blob-ID, sentroid, areal og form per figur.", qEn: "Build records preserving colour, local blob ID, centroid, area and shape for each object.", why: "Merk at ID 1 kan finnes i alle tre maskene: bruk for eksempel nøkkelen (farge, lokal ID). Samle først etter at hver maske er kontrollert; lagre $(u,v)$ og enheter eksplisitt.", whyEn: "ID 1 may occur in all three masks; use a key such as (colour, local ID). Combine only after checking each mask; store $(u,v)$ and units explicitly.", answer: "Unik (farge, ID)-nøkkel og én post per verifisert figur; ingen felles universell piksel-ID.", answerEn: "Unique (colour, ID) key and one record per verified shape; no universal shared pixel ID.", topics: [colour, regions] },
    { id: "robustness", n: 7, title: "Valgfri robusthetstest", titleEn: "Optional robustness check", q: "Undersøk hvordan terskel, støynivå og opprydding påvirker maskene og målene.", qEn: "Explore how threshold, noise and cleanup change masks and measurements.", why: "Test flere terskler på kopier, logg antall blobs, areal og sentroider. Sammenlign ønskede figurer før/etter; en penere maske er ikke automatisk mer riktig. Dette er valgfritt i Prac A.", whyEn: "Try multiple thresholds on copies and log blob count, area and centroids. Compare intended shapes before/after; a cleaner-looking mask need not be more correct. Prac A marks this as optional.", answer: "En kort tabell med parametre, observasjon og begrunnelse; ingen én fasitverdi.", answerEn: "A short table of parameters, observations and rationale; no single numerical answer.", topics: [filter, morphology, regions] },
  ].map((part): VisionCard => ({
    id: `w9-prac-${part.id}`, source: "Weeks 9&10 Prac A - Feature Extraction", sourcePage: part.n === 1 ? 1 : part.n <= 5 ? 2 : 3,
    verification: "derived", topics: part.topics,
    no: { title: `Prac A ${part.n}: ${part.title}`, prompt: part.q, solution: `### Stegvis arbeidsflyt\n\n1. Les den aktuelle masken som boolsk array og bevar originalen.\n2. ${part.why}\n3. Kontroller resultatet visuelt og oppgi valg av terskel, naboskap og enheter. Råbildet er ikke flyttet inn på nettsiden.`, answer: part.answer },
    en: { title: `Prac A ${part.n}: ${part.titleEn}`, prompt: part.qEn, solution: `### Step-by-step workflow\n\n1. Read the relevant mask as a Boolean array and preserve the original.\n2. ${part.whyEn}\n3. Inspect the result and report threshold, connectivity and units. The source image remains outside the website.`, answer: part.answerEn },
  })),
];

const week11: VisionCard[] = [
  {
    id: "w11-tutorial-area", source: "Week 11 Tutorial - Image Formation and Geometry", sourcePage: 10, verification: "derived", topics: [homography],
    no: { title: "Tutorial a: doble arealet", prompt: "Lag en homografi som dobler arealet av enhver plan figur.", solution: "### Determinant, ikke bare sidelengde\n\n1. Bruk en affin homografi med nederste rad $(0,0,1)$ slik at arealfaktoren er absoluttverdien av determinanten til øvre venstre $2\\times2$-blokk.\n2. Velg $H=\\operatorname{diag}(2,1,1)$. Da er $|\\det H_{2\\times2}|=2$ for alle figurer i planet.\n3. Et alternativ som skalerer likt i begge retninger er $\\operatorname{diag}(\\sqrt2,\\sqrt2,1)$. En perspektivterm ville vanligvis gitt posisjonsavhengig arealskala.", answer: "$H=\\operatorname{diag}(2,1,1)$ eller $H=\\operatorname{diag}(\\sqrt2,\\sqrt2,1)$." },
    en: { title: "Tutorial a: double planar area", prompt: "Give a homography that doubles the area of every planar shape.", solution: "### Determinant, not just side length\n\n1. Choose an affine homography with bottom row $(0,0,1)$; its area multiplier is the absolute determinant of the upper-left $2\\times2$ block.\n2. Set $H=\\operatorname{diag}(2,1,1)$; then $|\\det H_{2\\times2}|=2$ throughout the plane.\n3. Uniform scaling uses $\\operatorname{diag}(\\sqrt2,\\sqrt2,1)$. General perspective terms would make the area factor position-dependent.", answer: "$H=\\operatorname{diag}(2,1,1)$ or $H=\\operatorname{diag}(\\sqrt2,\\sqrt2,1)$." },
  },
  {
    id: "w11-tutorial-handedness", source: "Week 11 Tutorial - Image Formation and Geometry", sourcePage: 10, verification: "derived", topics: [homography, link("Rammer", "reference-frames")],
    no: { title: "Tutorial b: bytt håndthet", prompt: "Lag en homografi mellom en høyre- og en venstrehendt plan koordinatramme.", solution: "### Speil én akse\n\n1. En ren rotasjon har positiv determinant og bevarer orientering.\n2. Reflekter én akse: $H=\\operatorname{diag}(-1,1,1)$. Da er determinanten til 2D-blokken $-1$, og $(1,0)$ blir $(-1,0)$ mens $(0,1)$ beholdes.\n3. Et speil i y-aksen fungerer tilsvarende. Skriv hvilken retning avbildningen gjelder.", answer: "$H=\\operatorname{diag}(-1,1,1)$, med negativ 2D-determinant." },
    en: { title: "Tutorial b: reverse handedness", prompt: "Construct a homography between right- and left-handed planar coordinate frames.", solution: "### Reflect one axis\n\n1. A pure rotation has positive determinant and preserves orientation.\n2. Reflect one axis with $H=\\operatorname{diag}(-1,1,1)$: the 2D determinant is $-1$, $(1,0)$ maps to $(-1,0)$ while $(0,1)$ stays fixed.\n3. Reflecting the other axis also works. State the direction of the mapping.", answer: "$H=\\operatorname{diag}(-1,1,1)$ with a negative 2D determinant." },
  },
  {
    id: "w11-tutorial-transform", source: "Week 11 Tutorial - Image Formation and Geometry", sourcePage: 10, verification: "derived", topics: [homography],
    no: { title: "Tutorial c: transformer punkter begge veier", prompt: "Gitt $^A H_B=\\begin{bmatrix}10&5&500\\\\2&5&640\\\\0.1&0&1\\end{bmatrix}$, finn $^B p$ for $^A p=(240,320)$ og $^A p$ for $^B p=(1,1)$.", solution: "### Merk retningen før multiplikasjon\n\n1. $H$ sender B til A. For $^Bp=(1,1,1)^T$ fås $(515,647,1.1)$; divider de to første med $1.1$, så $^Ap=(5150/11,6470/11)$.\n2. Gå motsatt vei ved å løse $H\\tilde p_B\\sim(240,320,1)^T$. Sett $x,y$ som B-koordinater: $10x+5y+500=240(0.1x+1)$ og $2x+5y+640=320(0.1x+1)$.\n3. Subtraksjon gir $x=15/4$, deretter $y=-83/2$. Tilbakeprojiser for å kontrollere $(240,320)$; å bruke $H$ direkte fra A til B ville gitt feil ramme.", answer: "$^B p=(15/4,-83/2)=(3.75,-41.5)$; $^A p=(5150/11,6470/11)\\approx(468.18,588.18)$." },
    en: { title: "Tutorial c: transform points in both directions", prompt: "Given $^A H_B=\\begin{bmatrix}10&5&500\\\\2&5&640\\\\0.1&0&1\\end{bmatrix}$, find $^B p$ for $^A p=(240,320)$ and $^A p$ for $^B p=(1,1)$.", solution: "### Label direction before multiplying\n\n1. $H$ maps B to A. From $^Bp=(1,1,1)^T$ obtain $(515,647,1.1)$ and divide by $1.1$: $^Ap=(5150/11,6470/11)$.\n2. To go back, solve $H\\tilde p_B\\sim(240,320,1)^T$. With B coordinates $x,y$: $10x+5y+500=240(0.1x+1)$ and $2x+5y+640=320(0.1x+1)$.\n3. Subtract to find $x=15/4$, then $y=-83/2$. Project forward to recover $(240,320)$; applying $H$ directly in the reverse direction would use the wrong frame.", answer: "$^B p=(15/4,-83/2)=(3.75,-41.5)$; $^A p=(5150/11,6470/11)\\approx(468.18,588.18)$." },
  },
  {
    id: "w11-tutorial-camera-square", source: "Week 11 Tutorial - Image Formation and Geometry", sourcePage: 17, verification: "open", topics: [camera, optics],
    no: { title: "Tutorial: kamera over et 2 × 2 m kvadrat", prompt: "Et kamera ser loddrett ned fra 2 m over sentrum av et 2 × 2 m kvadrat. Velg største synsfelt fra 1,8–8 mm brennvidde, og finn hjørnepiksler dersom sensordata er kjent.", solution: "### Beregn det kildene tillater\n\n1. Kortest brennvidde $f=1.8\\,\\mathrm{mm}$ gir størst vinkel i idealmodellen. Velg kameraramme med alle hjørner ved dybde $Z_C=2\\,\\mathrm{m}$ og $(X_C,Y_C)=(\\pm1,\\pm1)\\,\\mathrm{m}$.\n2. Med pikselstørrelse $\\rho_u,\\rho_v$ og principal point $(u_0,v_0)$ blir $u=u_0\\pm f/(2\\rho_u)$ og $v=v_0\\pm f/(2\\rho_v)$, for konsistente lengdeenheter og valgt fortegn.\n3. Kilden lenker til tekniske kameradata, men lokale PDF-er gir ikke oppløsning, fysisk pikselstørrelse eller faktisk principal point. Derfor finnes ingen kontrollerbar numerisk pikselfasit her. Sjekk også at hjørnene ligger innen sensoren.", answer: "$f=1.8\\,\\mathrm{mm}$, $u=u_0\\pm f/(2\\rho_u)$ og $v=v_0\\pm f/(2\\rho_v)$; tallpiksler krever manglende kameradata." },
    en: { title: "Tutorial: camera above a 2 × 2 m square", prompt: "A downward-looking camera is 2 m above the centre of a 2 × 2 m square. Choose the widest field of view from 1.8–8 mm and determine corner pixels if sensor data are available.", solution: "### Calculate only what the sources permit\n\n1. The shortest focal length $f=1.8\\,\\mathrm{mm}$ yields the widest ideal view. Choose a camera frame with corners at depth $Z_C=2\\,\\mathrm{m}$ and $(X_C,Y_C)=(\\pm1,\\pm1)\\,\\mathrm{m}$.\n2. With pixel pitch $\\rho_u,\\rho_v$ and principal point $(u_0,v_0)$, use $u=u_0\\pm f/(2\\rho_u)$ and $v=v_0\\pm f/(2\\rho_v)$ in consistent units and the chosen axis convention.\n3. The tutorial links to a camera specification, but the locally supplied PDFs do not contain resolution, pixel pitch or principal point. Numerical pixel answers cannot be verified from these sources. Check visibility within the sensor as well.", answer: "$f=1.8\\,\\mathrm{mm}$, $u=u_0\\pm f/(2\\rho_u)$ and $v=v_0\\pm f/(2\\rho_v)$; numeric pixels require missing camera data." },
  },
  ...[
    { id: "segment", n: 1, no: "Segmenter nye bilder", en: "Segment new images", q: "Gjenbruk uke 10-pipelinen på Assessment 2.4-eksempelbilder; hvor mye måtte endres?", qEn: "Reuse the Week 10 pipeline on Assessment 2.4 example images; what had to change?", why: "Skill kalibreringsmarkører fra andre figurer, kontroller masker, blob-antall og endringer i terskler/ROI. Mange håndjusteringer tyder på svak generalisering.", whyEn: "Separate calibration markers from other shapes, inspect masks, blob counts and changes to thresholds/ROI. Many manual changes indicate limited generalisation.", answer: "Dokumentert maskekvalitet og liste over nødvendige tilpasninger; bildene er ikke med i den lokale uke-mappen.", answerEn: "Document mask quality and necessary adjustments; the images are not in the local week folder.", topics: [colour, regions] },
    { id: "order-markers", n: 2, no: "Sorter røde markører", en: "Order red markers", q: "Bestem en stabil rekkefølge på de røde kalibreringsmarkørene.", qEn: "Determine a stable order for the red calibration markers.", why: "Finn sentroider, velg en kjent startmarkør og sorter resten etter den avtalte orienteringen. Samme rekkefølge må brukes for bilde- og verdenslisten; vinkel alene bestemmer ikke første hjørne.", whyEn: "Find centroids, identify a known starting marker and order the rest by the agreed orientation. Image and world lists must match; angles alone do not identify the first corner.", answer: "En verifisert én-til-én-liste av markør-ID, piksel $(u,v)$ og fysisk $(X,Y)$; ingen tall uten eksempelbildene.", answerEn: "A verified one-to-one list of marker ID, pixel $(u,v)$ and physical $(X,Y)$; no numbers without the example images.", topics: [calibration] },
    { id: "estimate-h", n: 3, no: "Estimer homografien", en: "Estimate the homography", q: "Bruk ordnede bilde-/verdenspunkt til å finne en plan homografi.", qEn: "Use ordered image/world correspondences to estimate a planar homography.", why: "Bruk minst fire ikke-kollineære punktpar, merk $H_{W\\leftarrow I}$ eller inversen eksplisitt, og normaliser ved reprojeksjon. Mål feil på punkter som ikke ble brukt i tilpasningen; OpenCV er et mulig verktøy.", whyEn: "Use at least four non-collinear point pairs, label $H_{W\\leftarrow I}$ or its inverse explicitly, and normalise after reprojection. Measure error on held-out points; OpenCV is one possible tool.", answer: "Kalibrert $H$ med kontrollert retning og reprojeksjonsfeil; numeriske koeffisienter krever de manglende korrespondansene.", answerEn: "A calibrated $H$ with checked direction and reprojection error; numeric coefficients require the missing correspondences.", topics: [calibration, homography] },
    { id: "warp", n: 4, no: "Rett ut perspektivet", en: "Rectify the image", q: "Warp det perspektivforvrengte bildet tilbake til en plan visning. Er gamle sentroider fortsatt riktige?", qEn: "Warp the perspective-distorted image to a planar view. Are the old centroids still correct?", why: "Velg en skala fra meter til målpiksler, warpe bildet med riktig retningsmatrise, og enten transformer gamle sentroider eller mål nye fra det warpede bildet. Interpolasjon kan flytte målte sentroider litt.", whyEn: "Choose a world-to-target-pixel scale, warp using the correct direction matrix, and either transform old centroids or remeasure in the warped image. Interpolation can shift measured centroids slightly.", answer: "Gamle pikselkoordinater refererer til originalbildet og kan ikke brukes direkte i det warpede bildet.", answerEn: "Old pixel coordinates refer to the original image and cannot be used unchanged in the warped image.", topics: [calibration, homography] },
    { id: "world-shapes", n: 5, no: "Lagre andre former i verdensrammen", en: "Store other shapes in the world frame", q: "Legg verdenskoordinater for alle øvrige figurer til de lagrede blob-postene.", qEn: "Add world coordinates for all other shapes to the stored blob records.", why: "For hvert originalt sentroid $p=(u,v,1)$ beregn $\\tilde q=H_{W\\leftarrow I}p$ og $q=(\\tilde q_1/\\tilde q_3,\\tilde q_2/\\tilde q_3)$. Kontroller ikke-null nevner, enhet og plane antakelser; behold originalpiksel og kalibreringsversjon.", whyEn: "For each original centroid $p=(u,v,1)$ compute $\\tilde q=H_{W\\leftarrow I}p$ and $q=(\\tilde q_1/\\tilde q_3,\\tilde q_2/\\tilde q_3)$. Check nonzero denominator, units and planarity; retain the original pixel and calibration version.", answer: "Postene får $(X,Y)$ med enhet og kalibreringsreferanse; uten bildene finnes ingen tallfasit.", answerEn: "Records gain $(X,Y)$ with units and a calibration reference; there is no numeric answer without the images.", topics: [calibration, homography] },
  ].map((part): VisionCard => ({
    id: `w11-prac-${part.id}`, source: "Week 11 Prac - Homography, Warping and the Real World", sourcePage: part.n <= 3 ? 1 : 2,
    verification: "open", topics: part.topics,
    no: { title: `Prac ${part.n}: ${part.no}`, prompt: part.q, solution: `### Arbeid steg for steg\n\n1. Definer hvilke data fra forrige steg som kreves og kontroller koordinatrammen.\n2. ${part.why}\n3. Bevar mellomresultatet og verifiser med tilgjengelige markører eller bilder; oppgaven oppgir ikke tallfasit.`, answer: part.answer },
    en: { title: `Prac ${part.n}: ${part.en}`, prompt: part.qEn, solution: `### Work step by step\n\n1. Identify required data from the previous step and check the coordinate frame.\n2. ${part.whyEn}\n3. Preserve intermediate results and check against available markers/images; the sheet supplies no numeric answer key.`, answer: part.answerEn },
  })),
];

const cards = { 9: week9, 11: week11 };
export function egb339VisionProblems(week: number): Egb339Problem[] {
  return (cards[week as keyof typeof cards] ?? []).map(({ id, source, sourcePage, verification, topics, no }) => ({ id, source, sourcePage, verification, topics, ...no }));
}
const translated: Record<string, Egb339ProblemEn> = Object.fromEntries([...week9, ...week11].map(({ id, en }) => [id, en]));
export function egb339VisionProblemEn(id: string): Egb339ProblemEn | null { return translated[id] ?? null; }
