/** Presentation-only replacements for authored mathematical code spans.
 * Explicit allowlist: Python, code fences, unknown notation and source data stay untouched. */
export const EGB339_READABLE_FORMULAS: Record<string, string> = {
  "R(θ) = [[cos θ, -sin θ], [sin θ, cos θ]]": "R(\\theta)=\\begin{bmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{bmatrix}",
  "Rx(θ) = [[1,0,0],[0,cosθ,-sinθ],[0,sinθ,cosθ]]": "R_x(\\theta)=\\begin{bmatrix}1&0&0\\\\0&\\cos\\theta&-\\sin\\theta\\\\0&\\sin\\theta&\\cos\\theta\\end{bmatrix}",
  "Ry(θ) = [[cosθ,0,sinθ],[0,1,0],[-sinθ,0,cosθ]]": "R_y(\\theta)=\\begin{bmatrix}\\cos\\theta&0&\\sin\\theta\\\\0&1&0\\\\-\\sin\\theta&0&\\cos\\theta\\end{bmatrix}",
  "Rz(θ) = [[cosθ,-sinθ,0],[sinθ,cosθ,0],[0,0,1]]": "R_z(\\theta)=\\begin{bmatrix}\\cos\\theta&-\\sin\\theta&0\\\\\\sin\\theta&\\cos\\theta&0\\\\0&0&1\\end{bmatrix}",
  "RᵀR = I": "R^T R=I",
  "det(R) = +1": "\\det R=+1",
  "R⁻¹ = Rᵀ": "R^{-1}=R^T",
  "T = [[R, t], [0, 1]]": "T=\\begin{bmatrix}R&t\\\\0&1\\end{bmatrix}",
  "T = [[R, t], [0, 0, 1]]": "T=\\begin{bmatrix}R&t\\\\0\\;0&1\\end{bmatrix}",
  "T = [[R, t], [0 0 0, 1]]": "T=\\begin{bmatrix}R&t\\\\0\\;0\\;0&1\\end{bmatrix}",
  "T⁻¹ = [[Rᵀ, -Rᵀt], [0 0 0, 1]]": "T^{-1}=\\begin{bmatrix}R^T&-R^Tt\\\\0\\;0\\;0&1\\end{bmatrix}",
  "p = [x, y]ᵀ": "p=\\begin{bmatrix}x\\\\y\\end{bmatrix}",
  "p_h = [x, y, 1]ᵀ": "p_h=\\begin{bmatrix}x\\\\y\\\\1\\end{bmatrix}",
  "p₀ = R p_A": "p_0=R\\,p_A",
  "p_A = Rᵀ p₀": "p_A=R^T p_0",
  "p₀ = R p_A + t": "p_0=R\\,p_A+t",
  "T₀E = T₀1 T₁2 … TₙE": "{}^0T_E={}^0T_1\\,{}^1T_2\\cdots{}^nT_E",
  "T₀E": "{}^0T_E",
  "∂p/∂q": "\\partial p/\\partial q",
  "c(θ) = ||FK(θ) - p*||₂": "c(\\theta)=\\lVert\\operatorname{FK}(\\theta)-p^*\\rVert_2",
  "pₓ=L₁cos(θ₁)+L₂cos(θ₁+θ₂)": "p_x=L_1\\cos\\theta_1+L_2\\cos(\\theta_1+\\theta_2)",
  "pᵧ=L₁sin(θ₁)+L₂sin(θ₁+θ₂)": "p_y=L_1\\sin\\theta_1+L_2\\sin(\\theta_1+\\theta_2)",
  "J = [[-L₁sin(θ₁)-L₂sin(θ₁+θ₂), -L₂sin(θ₁+θ₂)], [L₁cos(θ₁)+L₂cos(θ₁+θ₂), L₂cos(θ₁+θ₂)]]": "J=\\begin{bmatrix}-L_1\\sin\\theta_1-L_2\\sin(\\theta_1+\\theta_2)&-L_2\\sin(\\theta_1+\\theta_2)\\\\L_1\\cos\\theta_1+L_2\\cos(\\theta_1+\\theta_2)&L_2\\cos(\\theta_1+\\theta_2)\\end{bmatrix}",
  "Jᵢⱼ(q)=∂pᵢ/∂qⱼ": "J_{ij}(q)=\\frac{\\partial p_i}{\\partial q_j}",
  "Jᵢⱼ = ∂pᵢ/∂qⱼ": "J_{ij}=\\frac{\\partial p_i}{\\partial q_j}",
  "∂f/∂x = 6x": "\\frac{\\partial f}{\\partial x}=6x",
  "∂f/∂y = 6y²": "\\frac{\\partial f}{\\partial y}=6y^2",
  "Δp≈J(q)Δq": "\\Delta p\\approx J(q)\\Delta q",
  "Δq≈J(q)⁻¹Δp": "\\Delta q\\approx J(q)^{-1}\\Delta p",
  "pₜ₊₁≈pₜ+Δp": "p_{t+1}\\approx p_t+\\Delta p",
  "qₜ₊₁≈qₜ+Δq": "q_{t+1}\\approx q_t+\\Delta q",
  "q̇=J(q)⁻¹ṗ": "\\dot q=J(q)^{-1}\\dot p",
  "q̃ = H⁻¹p": "\\tilde q=H^{-1}p",
  "B = P₂-P₁": "B=P_2-P_1",
  "A = O-P₁": "A=O-P_1",
  "C = P₁+tB": "C=P_1+tB",
  "d = ||O-C||₂": "d=\\lVert O-C\\rVert_2",

  // --- Extended allowlist: mathematical code spans → KaTeX -------------------
  // Frames and sets
  "{A}": "\\{A\\}",
  "{B}": "\\{B\\}",
  "{C}": "\\{C\\}",
  "{E}": "\\{E\\}",
  "{0}": "\\{0\\}",
  "SE(2)": "\\mathrm{SE}(2)",
  "SE(3)": "\\mathrm{SE}(3)",
  "SO(2)": "\\mathrm{SO}(2)",
  "SO(3)": "\\mathrm{SO}(3)",
  "R ∈ SO(2)": "R\\in\\mathrm{SO}(2)",
  "t ∈ ℝ²": "t\\in\\mathbb{R}^2",
  "R ∈ SO(3)": "R\\in\\mathrm{SO}(3)",
  "t ∈ ℝ³": "t\\in\\mathbb{R}^3",
  // Dimensions
  "3×3": "3\\times 3",
  "2×2": "2\\times 2",
  "4×4": "4\\times 4",
  "3×1": "3\\times 1",
  "m×n": "m\\times n",
  "n×p": "n\\times p",
  "m×p": "m\\times p",
  // Matrix literals used as mathematics
  "[[12,14],[43,50]]": "\\begin{bmatrix}12&14\\\\43&50\\end{bmatrix}",
  "[[1,2],[3,4]]": "\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix}",
  "[[5,6],[7,8]]": "\\begin{bmatrix}5&6\\\\7&8\\end{bmatrix}",
  "[[19,22],[43,50]]": "\\begin{bmatrix}19&22\\\\43&50\\end{bmatrix}",
  // Single-letter and short-form variables
  "q": "q",
  "p": "p",
  "n": "n",
  "m": "m",
  "u": "u",
  "v": "v",
  "x": "x",
  "y": "y",
  "z": "z",
  "t": "t",
  "d": "d",
  "r": "r",
  "i": "i",
  "A": "A",
  "B": "B",
  "C": "C",
  "O": "O",
  "R": "R",
  "T": "T",
  "H": "H",
  "N": "N",
  "θ": "\\theta",
  "i=0,…,n-1": "i=0,\\dots,n-1",
  // Kinematics expressions
  "p = FK(q)": "p=\\operatorname{FK}(q)",
  "p=FK(q)": "p=\\operatorname{FK}(q)",
  "J(q)": "J(q)",
  "R(q)": "R(q)",
  "p(q)": "p(q)",
  "FK(q)": "\\operatorname{FK}(q)",
  "p*": "p^*",
  "q̇": "\\dot q",
  "ṗ": "\\dot p",
  "Δp": "\\Delta p",
  "Δq": "\\Delta q",
  "p₀": "p_0",
  "p_A": "p_A",
  "p_h": "p_h",
  "pᵢ": "p_i",
  "pₓ": "p_x",
  "pᵧ": "p_y",
  "P₁": "P_1",
  "P₂": "P_2",
  "p̃": "\\tilde p",
  "p̃₃": "\\tilde p_3",
  "q̃": "\\tilde q",
  "q̃₃": "\\tilde q_3",
  "pₜ₊₁": "p_{t+1}",
  "qₜ₊₁": "q_{t+1}",
  "T⁻¹": "T^{-1}",
  "Jᵢⱼ": "J_{ij}",
  "∂pᵢ/∂qⱼ": "\\partial p_i/\\partial q_j",
  "ṗ = J(q)q̇": "\\dot p=J(q)\\dot q",
  "ṗ=J(q)q̇": "\\dot p=J(q)\\dot q",
  "q̇ = J(q)⁻¹ṗ": "\\dot q=J(q)^{-1}\\dot p",
  "Δp ≈ J(q)Δq": "\\Delta p\\approx J(q)\\Delta q",
  "Δq ≈ J(q)⁻¹Δp": "\\Delta q\\approx J(q)^{-1}\\Delta p",
  "t = (A·B)/(B·B)": "t=(A\\cdot B)/(B\\cdot B)",
  "v(t)": "v(t)",
  "dv/dt": "dv/dt",
  "f(x,y)=3x²+2y³": "f(x,y)=3x^2+2y^3",
  "d(sin x)/dx=cos x": "\\frac{d(\\sin x)}{dx}=\\cos x",
  "d(cos x)/dx=-sin x": "\\frac{d(\\cos x)}{dx}=-\\sin x",
  "p ~ Hq": "p\\sim Hq",
  "p ~ H q": "p\\sim H q",
  "p̃ = Hq": "\\tilde p=Hq",
  "C = 4πA/P²": "C=4\\pi A/P^2",
  "S = 16A/P²": "S=16A/P^2",
  "C=1": "C=1",
  "S=1": "S=1",
  "s = R+G+B": "s=R+G+B",
  "r=R/s": "r=R/s",
  "g=G/s": "g=G/s",
  "b=B/s": "b=B/s",
  "s>0": "s>0",
  "s=0": "s=0",
  "det(R) ≈ 1": "\\det R\\approx 1",
  "det(R) ≈ +1": "\\det R\\approx +1",
  "R.T @ R ≈ I": "R^T R\\approx I",
  "T @ p_h": "T\\,p_h",
  "R_x(α) @ R_z(β)": "R_x(\\alpha)\\,R_z(\\beta)",
  "R_z(β) @ R_x(α)": "R_z(\\beta)\\,R_x(\\alpha)",
  "Rx Ry": "R_x\\,R_y",
  "Ry Rx": "R_y\\,R_x",
  "[0, 0, 0, 1]": "\\begin{bmatrix}0&0&0&1\\end{bmatrix}",
  "[0,0,1]": "\\begin{bmatrix}0&0&1\\end{bmatrix}",
  "[0,0,0,1]": "\\begin{bmatrix}0&0&0&1\\end{bmatrix}",
  "[x, y, z, 1]ᵀ": "\\begin{bmatrix}x&y&z&1\\end{bmatrix}^T",
  "[0,1]": "[0,1]",
  "atan2(y, x)": "\\operatorname{atan2}(y, x)",
  "atan(y/x)": "\\operatorname{atan}(y/x)",
  // Robot parameters and FK equations in prose
  "L0": "L_0",
  "L1": "L_1",
  "L2": "L_2",
  "L3": "L_3",
  "L4": "L_4",
  "L0=138": "L_0=138",
  "L1=135": "L_1=135",
  "L2=147": "L_2=147",
  "L3=60": "L_3=60",
  "L4=-70": "L_4=-70",
  "L3=60 mm": "L_3=60\\ \\mathrm{mm}",
  "L4=80 mm": "L_4=80\\ \\mathrm{mm}",
  "L4=-70 mm": "L_4=-70\\ \\mathrm{mm}",
  "z=-5 mm": "z=-5\\ \\mathrm{mm}",
  "z=0": "z=0",
  "z=10": "z=10",
  "z=10 mm": "z=10\\ \\mathrm{mm}",
  "z≥10 mm": "z\\ge 10\\ \\mathrm{mm}",
  "|L1 - L2| ≤ r ≤ L1 + L2": "|L_1-L_2|\\le r\\le L_1+L_2",
  "r = L1 sin(q2) + L2 cos(q3) + L3": "r=L_1\\sin q_2+L_2\\cos q_3+L_3",
  "x = r cos(q1)": "x=r\\cos q_1",
  "y = r sin(q1)": "y=r\\sin q_1",
  "z = L0 + L1 cos(q2) - L2 sin(q3) - L4": "z=L_0+L_1\\cos q_2-L_2\\sin q_3-L_4",
  "max(0, (10/6)C - min(5, max(0.5(N-1), 0)))": "\\max\\bigl(0,\\tfrac{10}{6}C-\\min(5,\\max(0.5(N-1),0))\\bigr)",
  "pᵢ = pₛ + (pₑ-pₛ)i/(n-1)": "p_i=p_s+(p_e-p_s)\\,i/(n-1)",
  "(u,v)": "(u, v)",
};

export function egb339ReadableMath(markdown: string): string {
  let fence: string | null = null;
  return markdown.split("\n").map((line) => {
    const marker = line.match(/^\s*(`{3,}|~{3,})/);
    if (marker) {
      if (!fence) fence = marker[1];
      else if (marker[1][0] === fence[0] && marker[1].length >= fence.length) fence = null;
      return line;
    }
    if (fence) return line;
    const standalone = line.match(/^`([^`]+)`([.,;:]?)$/);
    if (standalone && EGB339_READABLE_FORMULAS[standalone[1]]) return "$$\n" + EGB339_READABLE_FORMULAS[standalone[1]] + standalone[2] + "\n$$";
    return line.replace(/`([^`\n]+)`/g, (original, expression: string) => EGB339_READABLE_FORMULAS[expression] ? "$" + EGB339_READABLE_FORMULAS[expression] + "$" : original);
  }).join("\n");
}
