/**
 * Flashcards for DAT109. Quizlet-stil — begrep på forsiden, forklaring på baksiden.
 *
 * Mål: 150-250 kort på tvers av alle temaer.
 */

import type { Flashcard } from "@/lib/quiz-types";

export const FLASHCARDS: Flashcard[] = [
  // ============================================================
  // MODELLERING (15)
  // ============================================================
  {
    id: "fc-modellering-brukstilfelle",
    topic: "modellering",
    front: "Brukstilfelle",
    back: "Et brukstilfelle (use case) beskriver en sammenhengende interaksjon mellom én eller flere aktører og systemet for å oppnå et mål. Det er en sekvens av handlinger, ikke et flytdiagram. Eksempel: 'Logg inn', 'Bestill billett'.",
    difficulty: "easy",
  },
  {
    id: "fc-modellering-aktor",
    topic: "modellering",
    front: "Aktør",
    back: "En aktør er en rolle som en bruker eller et eksternt system spiller når den interagerer med systemet vårt. Tegnes som strekfigur. Aktører er ALLTID utenfor systemgrensen. Eksempel: 'Kunde', 'Betalingstjeneste'.",
    difficulty: "easy",
  },
  {
    id: "fc-modellering-systemgrense",
    topic: "modellering",
    front: "Systemgrense",
    back: "Rektangelet i brukstilfellediagrammet som viser hva som er INNE i systemet (brukstilfellene) og hva som er UTENFOR (aktørene). Definerer omfanget vi modellerer.",
    difficulty: "easy",
  },
  {
    id: "fc-modellering-include",
    topic: "modellering",
    front: "<<include>>",
    back: "Brukstilfelle A include B betyr at A ALLTID utfører B som en del av sin flyt. Pilen peker FRA A TIL B. Eksempel: 'Bestill billett' <<include>> 'Logg inn' (når innlogging er obligatorisk).",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-extends",
    topic: "modellering",
    front: "<<extends>>",
    back: "Brukstilfelle B extends A betyr at B er en VALGFRI utvidelse av A som kjøres ved et bestemt extension-punkt. Pilen peker FRA B TIL A. Eksempel: 'Bruk rabattkode' <<extends>> 'Bestill billett'.",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-include-vs-extends",
    topic: "modellering",
    front: "Include vs extends",
    back: "Include = obligatorisk delfunksjon (alltid kjørt). Extends = valgfri tilleggsfunksjon (bare i visse tilfeller). Begge brukes for å unngå duplikat-flyt mellom brukstilfeller.",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-domenemodell",
    topic: "modellering",
    front: "Domenemodell",
    back: "Et konseptuelt klassediagram over substantivene i problemområdet (begreper, attributter, assosiasjoner). Viktig: domenemodellen inneholder ALDRI metoder — den er begrepskart, ikke kode.",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-multiplisitet",
    topic: "modellering",
    front: "Multiplisitet",
    back: "Antall objekter som kan være knyttet sammen i en assosiasjon. Skrives 1, 0..1, *, 1..*, 0..*. Eksempel: en Bestilling har 1..* Bestillingslinjer; en Kunde har 0..* Bestillinger.",
    difficulty: "easy",
  },
  {
    id: "fc-modellering-klassediagram",
    topic: "modellering",
    front: "Klassediagram-elementer",
    back: "Klasser (rektangel med tre rom: navn, attributter, metoder), assosiasjoner (linjer med multiplisitet), arv (åpen trekant), aggregering (åpen rombe), komposisjon (fylt rombe), avhengighet (stiplet pil).",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-sekvensdiagram",
    topic: "modellering",
    front: "Sekvensdiagram",
    back: "Viser meldinger mellom objekter over tid. Tid går nedover. Aktører/objekter har livslinjer (stiplet linje), aktiveringsbokser (rektangel) viser når et objekt er aktivt, piler er meldinger. Skal samsvare med brukstilfellebeskrivelsen.",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-livslinje",
    topic: "modellering",
    front: "Livslinje",
    back: "Den stiplede vertikale linjen under et objekt eller en aktør i et sekvensdiagram. Representerer objektets eksistens over tid. Avsluttes med X hvis objektet destrueres.",
    difficulty: "easy",
  },
  {
    id: "fc-modellering-aktiveringsboks",
    topic: "modellering",
    front: "Aktiveringsboks",
    back: "Det smale rektangelet på en livslinje som viser at objektet er aktivt (har kontroll/utfører kode). Tegnes mellom mottatt melding og retur-melding.",
    difficulty: "easy",
  },
  {
    id: "fc-modellering-fragment-loop",
    topic: "modellering",
    front: "loop-fragment",
    back: "Sammensatt fragment i sekvensdiagram som omslutter meldinger som gjentas. Skrives 'loop [betingelse]' eller 'loop [1..n]'. Brukes for iterasjon, f.eks. 'for hver bestillingslinje'.",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-fragment-alt",
    topic: "modellering",
    front: "alt-fragment",
    back: "Alternativ-fragment i sekvensdiagram (if/else). Delt med stiplet linje, hvert avsnitt har sin betingelse [...]. Bare ett avsnitt utføres. Brukes for å vise valg basert på vilkår.",
    difficulty: "medium",
  },
  {
    id: "fc-modellering-info-expert-sekvens",
    topic: "modellering",
    front: "GRASP-ekspert i sekvens",
    back: "Når du tegner sekvensdiagram, send meldingen til objektet som har informasjonen som trengs. Eks: 'beregn totalpris' bør gå til Bestilling (har bestillingslinjene), ikke til Kunde. Brettet kjenner Ruter → Brettet finner ruter, ikke Spilleren.",
    difficulty: "hard",
  },

  // ============================================================
  // OOP-FUNDAMENTER (Booch + ekstra) (16)
  // ============================================================
  {
    id: "fc-oop-fundamenter-oversikt",
    topic: "oop-fundamenter",
    front: "Booch sine 7 OO-egenskaper",
    back: "1) Abstraksjon, 2) Innkapsling, 3) Modularitet, 4) Hierarki, 5) Typing, 6) Samtidighet (concurrency), 7) Persistens. De fire første er HOVEDelementer, de tre siste er TILLEGG. V2024-tema.",
    difficulty: "hard",
  },
  {
    id: "fc-oop-fundamenter-abstraksjon",
    topic: "oop-fundamenter",
    front: "Abstraksjon (Booch)",
    back: "Å fokusere på de essensielle egenskapene til et objekt og ignorere irrelevante detaljer. En Bil-klasse har egenskapene som er viktige for konteksten (registreringsnummer, fart) — ikke skruene.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-innkapsling",
    topic: "oop-fundamenter",
    front: "Innkapsling (Booch)",
    back: "Å skille grensesnittet fra implementasjonen og skjule interne detaljer. Vanligvis ved private felter + public metoder. Beskytter objektets tilstand mot uønsket manipulasjon.",
    difficulty: "easy",
  },
  {
    id: "fc-oop-fundamenter-modularitet",
    topic: "oop-fundamenter",
    front: "Modularitet (Booch)",
    back: "Å dele systemet inn i sammenhengende, løst koblede moduler/pakker. Hver modul har et veldefinert ansvar. Forenkler vedlikehold, gjenbruk og testing.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-hierarki",
    topic: "oop-fundamenter",
    front: "Hierarki (Booch)",
    back: "En rangering eller ordning av abstraksjoner. Vanligst: arvshierarki ('is-a') og aggregeringshierarki ('part-of'). Lar oss organisere komplekse systemer i nivåer.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-typing",
    topic: "oop-fundamenter",
    front: "Typing (Booch)",
    back: "Håndhevelse av at et objekt av én type ikke kan brukes som et objekt av en annen type (uten konvertering). Sterk typing fanger feil ved kompilering. Java er sterkt typet.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-samtidighet",
    topic: "oop-fundamenter",
    front: "Samtidighet (Booch)",
    back: "Egenskapen som skiller aktive objekter (egen tråd) fra passive. Tillater at flere prosesser kjører parallelt. Krever synkronisering (f.eks. synchronized i Java) for å unngå race conditions.",
    difficulty: "hard",
  },
  {
    id: "fc-oop-fundamenter-persistens",
    topic: "oop-fundamenter",
    front: "Persistens (Booch)",
    back: "Egenskapen at et objekt eksisterer ut over tiden programmet kjører og/eller på tvers av maskiner. Realiseres med f.eks. database, fil, JPA. Et persistent objekt overlever programkjøringen.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-state-behaviour-identity",
    topic: "oop-fundamenter",
    front: "State, Behaviour, Identity",
    back: "De tre kjennetegnene til ethvert objekt: STATE = verdiene i feltene akkurat nå; BEHAVIOUR = metodene/operasjonene den kan utføre; IDENTITY = unik referanse som skiller det fra alle andre objekter med samme tilstand.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-klasse-vs-objekt",
    topic: "oop-fundamenter",
    front: "Klasse vs objekt",
    back: "Klasse = malen/oppskriften (definisjon av felter, metoder). Objekt = en konkret instans (med faktiske verdier i felter) i minnet ved kjøring. Mange objekter kan opprettes fra én klasse.",
    difficulty: "easy",
  },
  {
    id: "fc-oop-fundamenter-polymorphism",
    topic: "oop-fundamenter",
    front: "Polymorfi",
    back: "At samme melding (metodekall) kan håndteres ulikt av forskjellige objekttyper. Eksempel: Animal a = new Dog(); a.lyd() kaller Dog sin lyd. Realiseres med arv eller grensesnitt.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-arv",
    topic: "oop-fundamenter",
    front: "Arv",
    back: "Mekanisme der en subklasse arver felter og metoder fra en superklasse, og kan overstyre/legge til. Modellerer 'is-a'. Java støtter enkel arv mellom klasser, multippel arv mellom interface.",
    difficulty: "easy",
  },
  {
    id: "fc-oop-fundamenter-meldingsutveksling",
    topic: "oop-fundamenter",
    front: "Meldingsutveksling",
    back: "Objekter samhandler ved å SENDE MELDINGER (kalle metoder) til hverandre. Et objekt utfører ikke arbeid alene; det ber andre objekter om hjelp. Kjernen i objektorientert design.",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-grensesnitt",
    topic: "oop-fundamenter",
    front: "Grensesnitt (interface)",
    back: "Kontrakten — hvilke metoder et objekt må tilby — uten å bestemme hvordan. Skiller HVA fra HVORDAN. Klienter programmerer mot grensesnittet, ikke implementasjonen (Dependency Inversion).",
    difficulty: "medium",
  },
  {
    id: "fc-oop-fundamenter-instans",
    topic: "oop-fundamenter",
    front: "Instans",
    back: "Et konkret objekt opprettet fra en klasse. 'new Bil()' lager en NY instans av Bil-klassen. Hver instans har sin egen state men deler klassens metoder.",
    difficulty: "easy",
  },
  {
    id: "fc-oop-fundamenter-kohesjon",
    topic: "oop-fundamenter",
    front: "Høy kohesjon",
    back: "En klasse skal ha ÉN sammenhengende oppgave; alle metodene jobber med samme ansvar. Lav kohesjon = klassen gjør for mange ulike ting (god-klasse). Knyttet til SRP og GRASP.",
    difficulty: "medium",
  },

  // ============================================================
  // UML (14)
  // ============================================================
  {
    id: "fc-uml-hva",
    topic: "uml",
    front: "Hva er UML?",
    back: "Unified Modeling Language — et standardisert visuelt språk for å spesifisere, visualisere, konstruere og dokumentere artefakter i et programvaresystem. Et felles notasjonsspråk på tvers av prosjekter.",
    difficulty: "easy",
  },
  {
    id: "fc-uml-omg",
    topic: "uml",
    front: "OMG",
    back: "Object Management Group — den internasjonale standardiseringsorganisasjonen som vedlikeholder og utvikler UML-standarden. Sørger for at notasjonen er enhetlig på tvers av verktøy og land.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-fordeler",
    topic: "uml",
    front: "Fordeler ved UML",
    back: "Felles språk mellom utviklere, kunder og analytikere; visualiserer kompleks struktur; støtter både analyse og design; verktøy-uavhengig; fasiliterer dokumentasjon og vedlikehold.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-brukstilfellediagram",
    topic: "uml",
    front: "Brukstilfellediagram",
    back: "Viser systemets funksjonalitet sett fra utsiden: aktører (utenfor systemgrensen) og brukstilfeller (inne). Brukes til kravinnsamling og avgrensning av systemet.",
    difficulty: "easy",
  },
  {
    id: "fc-uml-klassediagram",
    topic: "uml",
    front: "Klassediagram",
    back: "Statisk strukturdiagram som viser klasser, attributter, metoder og relasjoner (assosiasjoner, arv, aggregering, komposisjon). Grunnlag for både domenemodell og designmodell.",
    difficulty: "easy",
  },
  {
    id: "fc-uml-sekvensdiagram",
    topic: "uml",
    front: "Sekvensdiagram",
    back: "Dynamisk diagram som viser meldingsutveksling mellom objekter over tid. Brukes for å beskrive hvordan ett brukstilfelle realiseres internt.",
    difficulty: "easy",
  },
  {
    id: "fc-uml-tilstandsdiagram",
    topic: "uml",
    front: "Tilstandsdiagram",
    back: "Viser hvilke tilstander et objekt kan være i, og hvilke hendelser som forårsaker overganger. Eksempel: Bestilling kan være 'Opprettet' → 'Betalt' → 'Sendt' → 'Mottatt'.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-aktivitetsdiagram",
    topic: "uml",
    front: "Aktivitetsdiagram",
    back: "Et flytdiagram som viser arbeidsflyt eller algoritmeflyt — handlinger, valg (rombe), parallelle spor (synkroniseringsbar). Likner et flytskjema, men i UML-notasjon.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-komponentdiagram",
    topic: "uml",
    front: "Komponentdiagram",
    back: "Viser fysiske/logiske komponenter i systemet og deres avhengigheter via tilbudte og påkrevde grensesnitt. Brukes i arkitekturbeskrivelse.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-utplasseringsdiagram",
    topic: "uml",
    front: "Utplasseringsdiagram",
    back: "Deployment diagram — viser hvor i den fysiske infrastrukturen (servere, klienter) de ulike komponentene kjøres. Brukes til distribuerings- og driftsplanlegging.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-synlighet-public",
    topic: "uml",
    front: "+ (UML-synlighet)",
    back: "Public — attributtet/metoden er synlig for alle. Mappes til 'public' i Java. Eksempel i UML: + getNavn(): String",
    difficulty: "easy",
  },
  {
    id: "fc-uml-synlighet-private",
    topic: "uml",
    front: "- (UML-synlighet)",
    back: "Private — bare synlig innenfor egen klasse. Mappes til 'private' i Java. Eksempel: - alder: int",
    difficulty: "easy",
  },
  {
    id: "fc-uml-synlighet-protected",
    topic: "uml",
    front: "# (UML-synlighet)",
    back: "Protected — synlig i egen klasse og subklasser. Mappes til 'protected' i Java. Brukes når subklasser trenger tilgang.",
    difficulty: "medium",
  },
  {
    id: "fc-uml-synlighet-package",
    topic: "uml",
    front: "~ (UML-synlighet)",
    back: "Package — synlig for klasser i samme pakke. Mappes til Java sin default visibility (ingen modifikator).",
    difficulty: "medium",
  },

  // ============================================================
  // SOLID (14)
  // ============================================================
  {
    id: "fc-solid-srp",
    topic: "solid",
    front: "S i SOLID",
    back: "Single Responsibility Principle (SRP): En klasse skal ha kun ÉN grunn til å endre seg — ett ansvar. Hvis en Rapport-klasse både formaterer og lagrer, bryter den SRP.",
    difficulty: "easy",
  },
  {
    id: "fc-solid-ocp",
    topic: "solid",
    front: "O i SOLID",
    back: "Open/Closed Principle (OCP): Klasser skal være ÅPNE for utvidelse, men LUKKET for endring. Bruk arv/strategimønster slik at ny funksjonalitet legges til uten å endre eksisterende kode.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-lsp",
    topic: "solid",
    front: "L i SOLID",
    back: "Liskov Substitution Principle (LSP): Subklasser skal kunne erstatte superklasser uten at programmet oppfører seg feil. Klassisk brudd: subklasse kaster UnsupportedOperationException.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-isp",
    topic: "solid",
    front: "I i SOLID",
    back: "Interface Segregation Principle (ISP): Klienter skal ikke tvinges til å være avhengige av metoder de ikke bruker. Lag heller flere små, fokuserte interface enn ett stort 'fat interface'.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-dip",
    topic: "solid",
    front: "D i SOLID",
    back: "Dependency Inversion Principle (DIP): Avhengig av abstraksjoner, ikke konkrete klasser. Høynivåmoduler skal ikke avhenge av lavnivå — begge skal avhenge av interface.",
    difficulty: "hard",
  },
  {
    id: "fc-solid-srp-eksempel",
    topic: "solid",
    front: "SRP-brudd (eksempel)",
    back: "Klassen Faktura beregner totalsum, formaterer som PDF OG sender e-post. Tre ansvar = tre grunner til endring. Splitt i FakturaBeregner, FakturaFormatter, FakturaSender.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-ocp-eksempel",
    topic: "solid",
    front: "OCP-brudd (eksempel)",
    back: "En metode beregnArealet bruker if/else over alle figurtyper (Sirkel, Rektangel, ...). Ny figur krever endring i metoden. Bedre: hver Figur-subklasse implementerer beregnAreal() selv (polymorfi).",
    difficulty: "medium",
  },
  {
    id: "fc-solid-lsp-brudd",
    topic: "solid",
    front: "LSP-brudd (klassisk)",
    back: "Square arver Rectangle og overstyrer setBredde slik at høyde også endres. Kode som forventer Rectangle-oppførsel oppfører seg feil. Square IS-NOT-A Rectangle i objektorientert forstand.",
    difficulty: "hard",
  },
  {
    id: "fc-solid-isp-brudd",
    topic: "solid",
    front: "ISP-brudd (eksempel)",
    back: "Interface 'Maskin' har print(), scan(), fax() — men en SimpelSkriver må implementere alle tre. Splitt i Skriver, Scanner, Fax så klasser velger det de trenger.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-dip-eksempel",
    topic: "solid",
    front: "DIP i praksis",
    back: "OrdreService skal IKKE 'new MySQLDatabase()'. I stedet ta inn en OrdreRepository (interface) i konstruktøren. Da kan databasen byttes uten å endre OrdreService — viktig for testbarhet.",
    difficulty: "hard",
  },
  {
    id: "fc-solid-formal",
    topic: "solid",
    front: "Hva er SOLID for?",
    back: "Et sett designprinsipper (Robert C. Martin) som skal gjøre objektorientert kode lettere å vedlikeholde, utvide og teste. Reduserer 'rigidity', 'fragility' og 'immobility' i kodebasen.",
    difficulty: "easy",
  },
  {
    id: "fc-solid-code-smell",
    topic: "solid",
    front: "Code smell",
    back: "Et tegn i koden på underliggende designproblem — f.eks. lange metoder, store klasser, lange parameterlister, duplikat kode, switch-statements. Smells indikerer ofte SOLID-brudd.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-god-class",
    topic: "solid",
    front: "God-klasse (smell)",
    back: "En klasse som gjør for mye og kan/vet alt. Klassisk SRP-brudd. Vanlig i prosedyrekode portet til OO. Skal splittes i flere klasser med klare ansvar.",
    difficulty: "medium",
  },
  {
    id: "fc-solid-shotgun-surgery",
    topic: "solid",
    front: "Shotgun surgery",
    back: "Smell der én logisk endring krever små endringer i mange klasser. Indikerer at ansvar er spredt utover (lav kohesjon, høy kobling). Refaktorer ved å samle ansvaret i én modul.",
    difficulty: "hard",
  },

  // ============================================================
  // GRASP (14)
  // ============================================================
  {
    id: "fc-grasp-info-expert",
    topic: "grasp",
    front: "Information Expert",
    back: "GRASP-prinsipp: Tildel ansvaret til klassen som har informasjonen som trengs for å utføre oppgaven. Eks: Brettet kjenner Ruter → Brettet finner ruter, ikke Spilleren.",
    difficulty: "easy",
  },
  {
    id: "fc-grasp-creator",
    topic: "grasp",
    front: "Creator",
    back: "Klasse B oppretter A hvis B inneholder/aggregerer A, har dataene for å initialisere A, eller bruker A tett. Eks: Bestilling oppretter Bestillingslinje (siden Bestilling inneholder linjene).",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-controller",
    topic: "grasp",
    front: "Controller",
    back: "Tildel ansvaret for å håndtere systemhendelser fra UI til en kontrollerklasse — enten 'fasade'-kontroller (representerer systemet/use case) eller 'domene'-kontroller. Skiller UI fra forretningslogikk.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-low-coupling",
    topic: "grasp",
    front: "Low Coupling",
    back: "Tildel ansvar slik at klasser har FÅ avhengigheter til andre. Lavt koblede klasser er lettere å gjenbruke, vedlikeholde og forstå. Vurder dette ved hvert designvalg.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-high-cohesion",
    topic: "grasp",
    front: "High Cohesion",
    back: "Tildel ansvar slik at en klasse holdes fokusert — alle metoder/felter jobber mot samme oppgave. Høy kohesjon = lett å forstå og vedlikeholde. Kombineres ofte med Low Coupling.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-polymorphism",
    topic: "grasp",
    front: "Polymorphism (GRASP)",
    back: "Når oppførsel varierer med type, bruk polymorfi (override) i stedet for if/else over typer. Eks: Animal.lyd() implementeres ulikt i Hund/Katt — kalleren vet ikke typen.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-pure-fabrication",
    topic: "grasp",
    front: "Pure Fabrication",
    back: "Et objekt som IKKE finnes i domenet, oppfunnet for å oppnå Low Coupling/High Cohesion. Eks: BestillingRepository (domenet kjenner ikke 'repository', men vi trenger ett for persistens).",
    difficulty: "hard",
  },
  {
    id: "fc-grasp-indirection",
    topic: "grasp",
    front: "Indirection",
    back: "Sett et mellomledd (objekt) mellom to klasser for å redusere kobling. Eks: en Mediator/Adapter mellom UI og forretningslogikk. Adapter-mønsteret er klassisk Indirection.",
    difficulty: "hard",
  },
  {
    id: "fc-grasp-protected-variations",
    topic: "grasp",
    front: "Protected Variations",
    back: "Identifiser punkter der ting kan variere/endre seg, og innkapsle dem bak et stabilt grensesnitt. Beskytter resten av systemet mot endringer. Tilsvarer 'programmer mot interface'.",
    difficulty: "hard",
  },
  {
    id: "fc-grasp-9-monstre",
    topic: "grasp",
    front: "GRASP — 9 mønstre",
    back: "Information Expert, Creator, Controller, Low Coupling, High Cohesion, Polymorphism, Pure Fabrication, Indirection, Protected Variations. Generelle prinsipper for å tildele ansvar i OO-design.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-controller-eksempel",
    topic: "grasp",
    front: "Controller (eksempel)",
    back: "I monopol-spillet er Spillet en use-case-controller som mottar 'kastTerning'-hendelsen fra UI. Spillet delegerer videre til Brett, Spiller osv. UI vet ingenting om domenet.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-naar-info-expert",
    topic: "grasp",
    front: "Når brukes Information Expert?",
    back: "Når du skal bestemme hvilken klasse som skal ha en metode/operasjon. Spør: 'Hvilken klasse har dataene den trenger?' — den klassen får ansvaret. Førstevalg ved ansvarstildeling.",
    difficulty: "medium",
  },
  {
    id: "fc-grasp-naar-pure-fabrication",
    topic: "grasp",
    front: "Når brukes Pure Fabrication?",
    back: "Når Information Expert ville gitt lav kohesjon eller høy kobling — typisk ved tekniske ansvar (persistens, logging, sikkerhet). Lager en 'kunstig' klasse som ikke finnes i domenet.",
    difficulty: "hard",
  },
  {
    id: "fc-grasp-info-expert-monopol",
    topic: "grasp",
    front: "Info Expert (monopol)",
    back: "Hvem skal beregne husleie? Tomten — den vet hvor mye leien er, hvor mange hus, og fargegruppe-eierskap. Spilleren har bare pengene; Brettet har bare oversikten.",
    difficulty: "medium",
  },

  // ============================================================
  // UTFORMINGSPRINSIPPER (14)
  // ============================================================
  {
    id: "fc-utforming-kiss",
    topic: "utformingsprinsipper",
    front: "KISS",
    back: "Keep It Simple, Stupid — velg den enkleste løsningen som virker. Unngå overengineering. Enkel kode er lettere å lese, teste og vedlikeholde. Kompleksitet skal være berettiget.",
    difficulty: "easy",
  },
  {
    id: "fc-utforming-yagni",
    topic: "utformingsprinsipper",
    front: "YAGNI",
    back: "You Ain't Gonna Need It — ikke bygg funksjonalitet 'for fremtiden'. Implementer bare det det er behov for nå. Unngår bortkastet arbeid og unødvendig kompleksitet. XP-prinsipp.",
    difficulty: "easy",
  },
  {
    id: "fc-utforming-dry",
    topic: "utformingsprinsipper",
    front: "DRY",
    back: "Don't Repeat Yourself — kunnskap skal ha én entydig representasjon i systemet. Duplikat kode betyr duplikat vedlikehold og risiko for inkonsistens. Refaktorer ut til felles funksjon/klasse.",
    difficulty: "easy",
  },
  {
    id: "fc-utforming-arv",
    topic: "utformingsprinsipper",
    front: "Arv (is-a)",
    back: "Spesialisering: en subklasse er en variant av superklassen. Hund IS-A Dyr. Brukes når subtypen har tilleggsegenskaper og samme grunnoppførsel. Tett kobling — endringer forplanter seg.",
    difficulty: "medium",
  },
  {
    id: "fc-utforming-komposisjon",
    topic: "utformingsprinsipper",
    front: "Komposisjon",
    back: "Et objekt EIER andre objekter som del av seg (sterk del-helhet). Når helheten dør, dør delene. Tegnes med fylt rombe. Eks: Bil 'består av' Motor — Motoren overlever ikke uten Bilen.",
    difficulty: "medium",
  },
  {
    id: "fc-utforming-aggregering",
    topic: "utformingsprinsipper",
    front: "Aggregering",
    back: "Svakere del-helhet enn komposisjon — delene kan eksistere uten helheten. Tegnes med åpen rombe. Eks: Avdeling har Ansatte, men Ansatte overlever Avdelingens nedleggelse.",
    difficulty: "medium",
  },
  {
    id: "fc-utforming-spesialisering",
    topic: "utformingsprinsipper",
    front: "Spesialisering",
    back: "Når en subklasse legger til/forfiner egenskaper utover superklassen. Snur opp-ned: man identifiserer fellesnevnere og generaliserer ('generalisering') eller deler opp i subtyper ('spesialisering'). KRITISK V2024-tema.",
    difficulty: "hard",
  },
  {
    id: "fc-utforming-arv-vs-komposisjon",
    topic: "utformingsprinsipper",
    front: "Arv vs komposisjon",
    back: "'Favor composition over inheritance' (GoF). Komposisjon gir lavere kobling, mer fleksibilitet (kan bytte deler ved kjøring), unngår dyp arvshierarki. Arv brukes når 'is-a' faktisk holder.",
    difficulty: "hard",
  },
  {
    id: "fc-utforming-tilstandshierarki",
    topic: "utformingsprinsipper",
    front: "Tilstandshierarki",
    back: "Når en klasse har sterkt forskjellig oppførsel basert på tilstand, kan tilstanden modelleres som subklasser (State-mønsteret) i stedet for if/else over en tilstandsvariabel. Eks: Bestilling → Opprettet, Betalt, Sendt.",
    difficulty: "hard",
  },
  {
    id: "fc-utforming-assosiasjon",
    topic: "utformingsprinsipper",
    front: "Assosiasjon",
    back: "En generell relasjon mellom to klasser — den ene 'kjenner' den andre. Tegnes som en linje i klassediagram. Aggregering og komposisjon er spesialformer av assosiasjon.",
    difficulty: "easy",
  },
  {
    id: "fc-utforming-avhengighet",
    topic: "utformingsprinsipper",
    front: "Avhengighet",
    back: "Den svakeste relasjonen mellom klasser — A bruker B kortvarig (parameter, lokal variabel). Tegnes som stiplet pil. Endring i B kan påvirke A.",
    difficulty: "medium",
  },
  {
    id: "fc-utforming-komposisjon-eksempel",
    topic: "utformingsprinsipper",
    front: "Komposisjon (eksempel)",
    back: "I stedet for at Loggable arver fra noe, INJISER en Logger i konstruktøren: new OrdreService(new FilLogger()). Da kan vi bytte til ConsoleLogger eller MockLogger uten å endre OrdreService.",
    difficulty: "medium",
  },
  {
    id: "fc-utforming-spesialisering-eksempel",
    topic: "utformingsprinsipper",
    front: "Spesialisering (eksempel)",
    back: "Vi har klassen Bil. Senere oppdager vi at Elbil har egne egenskaper (batterikapasitet, ladetid). Da SPESIALISERER vi Bil med subklassen Elbil — og kanskje Bensinbil — uten å endre Bil.",
    difficulty: "medium",
  },
  {
    id: "fc-utforming-generalisering",
    topic: "utformingsprinsipper",
    front: "Generalisering",
    back: "Motsatt av spesialisering — vi finner felles egenskaper i flere klasser og trekker dem opp til en ny superklasse. Hund og Katt har felles → Dyr. Reduserer duplikasjon.",
    difficulty: "medium",
  },

  // ============================================================
  // SCRUM (16)
  // ============================================================
  {
    id: "fc-scrum-product-owner",
    topic: "scrum",
    front: "Product Owner",
    back: "Eier produktets verdi. Prioriterer Product Backlog, definerer hva som skal bygges (men ikke hvordan), tar imot Inkrementet, og er bindeleddet mot kunder/brukere. Én person, ikke en komité.",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-scrum-master",
    topic: "scrum",
    front: "Scrum Master",
    back: "Tjenende leder (servant leader) — fasiliterer Scrum-praksisene, fjerner hindringer for teamet og coacher organisasjonen i Scrum. Er IKKE prosjektleder eller teknisk leder.",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-team",
    topic: "scrum",
    front: "Utviklingsteam",
    back: "Tverrfaglig, selvorganisert team (typisk 3-9 personer) som leverer Inkrementet. Felles ansvar — ingen titler internt. Bestemmer selv HVORDAN arbeidet utføres.",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-product-backlog",
    topic: "scrum",
    front: "Product Backlog",
    back: "Prioritert liste over alt arbeidet som potensielt skal gjøres på produktet. Eid og vedlikeholdt av Product Owner. Item høyt på listen er finere detaljert; lavt på listen er grovere.",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-sprint-backlog",
    topic: "scrum",
    front: "Sprint Backlog",
    back: "Settet med Product Backlog-items teamet har valgt for sprinten + en plan for å levere Inkrementet. Eid av teamet. Oppdateres daglig (typisk i Daily Scrum).",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-inkrement",
    topic: "scrum",
    front: "Inkrement",
    back: "Summen av alt fullført arbeid i sprinten + tidligere inkrementer. Skal være 'Done' iht. Definition of Done og potensielt utgivelsesklart. Demonstreres i Sprint Review.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-sprint",
    topic: "scrum",
    front: "Sprint",
    back: "Tidsboks (1-4 uker, vanligvis 2) der teamet leverer et brukbart, potensielt utgivelsesklart Inkrement. Sprintens lengde og mål endres ikke underveis. En ny sprint starter rett etter forrige.",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-sprint-planning",
    topic: "scrum",
    front: "Sprint Planning",
    back: "Møtet som starter sprinten. Teamet bestemmer sprintmål og hvilke backlog-items som tas inn. To deler: HVA (med PO) og HVORDAN (uten PO). Tidsboks: maks 8 timer for 4-ukers sprint.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-daily",
    topic: "scrum",
    front: "Daily Scrum",
    back: "15-minutters daglig stand-up der teamet inspiserer fremdriften mot sprintmålet og planlegger neste 24 timer. Tre vanlige spørsmål: hva gjorde jeg, hva skal jeg gjøre, har jeg blokkere? Bare teamet snakker.",
    difficulty: "easy",
  },
  {
    id: "fc-scrum-review",
    topic: "scrum",
    front: "Sprint Review",
    back: "Møtet på slutten av sprinten der Inkrementet demonstreres for Product Owner og interessenter. Innspill samles for å justere Product Backlog. Ikke et statusmøte — det er et samarbeidsmøte.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-retrospective",
    topic: "scrum",
    front: "Sprint Retrospective",
    back: "Møtet etter Sprint Review der teamet inspiserer SEG SELV — prosess, samarbeid, verktøy — og finner forbedringer for neste sprint. Skal gi minst ett konkret tiltak.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-burndown",
    topic: "scrum",
    front: "Burndown chart",
    back: "Graf som viser gjenstående arbeid i sprinten over tid. Y-akse = arbeid igjen, X-akse = dager. Idealt en jevn nedgang til 0. Brukes av teamet for å se om de er i rute.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-definition-of-done",
    topic: "scrum",
    front: "Definition of Done",
    back: "Felles forståelse i teamet av hva som må være på plass før et item regnes som ferdig (kodet, testet, dokumentert, kodegjennomgått, deployet osv.). Sikrer kvalitet og forutsigbarhet.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-velocity",
    topic: "scrum",
    front: "Velocity",
    back: "Mål på hvor mye arbeid (story points) teamet typisk fullfører per sprint. Brukes til å estimere hvor mye som realistisk kan tas inn neste sprint. Kun gyldig som teamets eget måltall — ikke for å sammenligne team.",
    difficulty: "hard",
  },
  {
    id: "fc-scrum-user-story",
    topic: "scrum",
    front: "User story",
    back: "Et lite, brukerorientert krav på formen 'Som <rolle> ønsker jeg <funksjon> slik at <verdi>'. Kombineres med akseptansekriterier. Holdes kort for samtale, ikke som fullstendig spec.",
    difficulty: "medium",
  },
  {
    id: "fc-scrum-tidsboks",
    topic: "scrum",
    front: "Tidsboks (Scrum)",
    back: "Maksimal varighet for en aktivitet. Sprint 1-4 uker, Sprint Planning maks 8 t (for 4 uker), Daily 15 min, Review maks 4 t, Retro maks 3 t. Skaper rytme og tvinger fokus.",
    difficulty: "medium",
  },

  // ============================================================
  // XP (15)
  // ============================================================
  {
    id: "fc-xp-hva",
    topic: "xp",
    front: "Hva er XP?",
    back: "Extreme Programming — smidig metodikk (Kent Beck, sent 1990-tall) som tar gode praksiser til ekstremen: hvis testing er bra, test alltid (TDD); hvis kodegjennomgang er bra, gjør det kontinuerlig (parprogrammering).",
    difficulty: "easy",
  },
  {
    id: "fc-xp-enkelhet",
    topic: "xp",
    front: "Enkelhet (XP)",
    back: "Gjør den enkleste tingen som virker — ikke bygg for fremtidige antatte behov. Reduserer kompleksitet og risiko. Tett knyttet til YAGNI og KISS.",
    difficulty: "easy",
  },
  {
    id: "fc-xp-kommunikasjon",
    topic: "xp",
    front: "Kommunikasjon (XP)",
    back: "Verdsett ansikt-til-ansikt-samarbeid framfor tunge dokumenter. Parprogrammering, on-site customer og felles kontorlandskap støtter denne verdien.",
    difficulty: "easy",
  },
  {
    id: "fc-xp-tilbakemelding",
    topic: "xp",
    front: "Tilbakemelding (XP)",
    back: "Få rask tilbakemelding fra kode (tester, CI), team (parprogrammering), kunde (korte iterasjoner). Korte loops gjør at feil oppdages tidlig og rettes billig.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-respekt",
    topic: "xp",
    front: "Respekt (XP)",
    back: "Hver enkelt på teamet bidrar med verdi og fortjener respekt. Lagt til som femte verdi i 2. utgave av XP-boken. Grunnlag for godt samarbeid og psykologisk trygghet.",
    difficulty: "easy",
  },
  {
    id: "fc-xp-mot",
    topic: "xp",
    front: "Mot (XP)",
    back: "Mot til å si sannheten om fremdrift, til å kaste kode som ikke virker, til å refaktorere, til å si 'nei' til urealistiske krav. Uten mot blir de andre verdiene tannløse.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-parprogrammering",
    topic: "xp",
    front: "Parprogrammering",
    back: "To programmerere ved én datamaskin — én skriver (driver), én vurderer (navigator). Gir kontinuerlig kodegjennomgang, kunnskapsdeling og færre defekter. Bytt rolle ofte.",
    difficulty: "easy",
  },
  {
    id: "fc-xp-tdd-praksis",
    topic: "xp",
    front: "TDD (XP-praksis)",
    back: "Test-Driven Development — skriv testen FØRST, så minimum kode for å bestå, så refaktorer. En av XPs viktigste tekniske praksiser. Sikrer at all kode er testet og at design ledes av krav.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-ci",
    topic: "xp",
    front: "Kontinuerlig integrasjon (XP)",
    back: "All kode integreres flere ganger daglig i felles hovedgren. Automatiske tester kjøres ved hver integrasjon. Holder hovedgrenen alltid grønn. Reduserer 'integration hell'.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-refactoring",
    topic: "xp",
    front: "Refaktorering (XP)",
    back: "Kontinuerlig forbedring av kodens design uten å endre oppførsel. Gjøres trygt fordi vi har testdekning. Holder kodebasen ren og fleksibel — motvirker entropi.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-collective-ownership",
    topic: "xp",
    front: "Kollektivt eierskap",
    back: "Hvem som helst på teamet kan endre hvilken som helst kode. Ingen 'min kode'/'din kode'. Krever kodestandarder og testdekning, men eliminerer flaskehalser og hever felles kompetanse.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-coding-standard",
    topic: "xp",
    front: "Kodestandarder (XP)",
    back: "Felles avtaler om navngivning, formattering og struktur. Forutsetning for kollektivt eierskap — koden ser lik ut uavhengig av forfatter. Automatiseres med linters/formatters.",
    difficulty: "easy",
  },
  {
    id: "fc-xp-small-releases",
    topic: "xp",
    front: "Korte leveranser",
    back: "Slipp små, fungerende leveranser ofte (uker, ikke måneder). Gir tidlig verdi, rask tilbakemelding og redusert risiko. Tett knyttet til CI/CD.",
    difficulty: "easy",
  },
  {
    id: "fc-xp-on-site-customer",
    topic: "xp",
    front: "On-site customer",
    back: "Kundens representant er fysisk til stede (eller alltid tilgjengelig) for å svare på spørsmål, prioritere og akseptere arbeid. Reduserer ventetid og misforståelser.",
    difficulty: "medium",
  },
  {
    id: "fc-xp-40-timer",
    topic: "xp",
    front: "40-timers uke",
    back: "Sustainable pace — utviklere skal ikke jobbe overtid systematisk. Trøtte folk lager dårlig kode. Begrenser brenneut og holder kvalitet og produktivitet jevn over tid.",
    difficulty: "easy",
  },

  // ============================================================
  // TDD (15)
  // ============================================================
  {
    id: "fc-tdd-red",
    topic: "tdd",
    front: "Red (TDD)",
    back: "Steg 1 i Red-Green-Refactor: skriv en NY test som beskriver ønsket oppførsel — den feiler (rød) fordi koden ikke finnes ennå. Bekrefter at testen faktisk tester noe.",
    difficulty: "easy",
  },
  {
    id: "fc-tdd-green",
    topic: "tdd",
    front: "Green (TDD)",
    back: "Steg 2: skriv MINIMUM kode som får testen til å gå grønn. Lov å være 'stygg' — målet er bare å passere testen. Demonstrerer at du har en fungerende implementasjon.",
    difficulty: "easy",
  },
  {
    id: "fc-tdd-refactor",
    topic: "tdd",
    front: "Refactor (TDD)",
    back: "Steg 3: rydd opp koden uten å endre oppførsel — testene skal fortsatt være grønne. Fjern duplikasjon, gi bedre navn, splitt opp metoder. Trygt fordi tester fanger regresjoner.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-syklus",
    topic: "tdd",
    front: "Red-Green-Refactor",
    back: "Den korte TDD-syklusen: skriv feilende test → få den grønn med minimum kode → forbedre designet. Gjentas i sekunder/minutter, ikke timer. Bygger systemet trinnvis med testdekning.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-dummy",
    topic: "tdd",
    front: "Dummy",
    back: "Et test-objekt som sendes inn bare fordi metodesignaturen krever det, men aldri brukes. Eks: en null-aktig parameter for å oppfylle konstruktøren. Enkleste form for test double.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-stub",
    topic: "tdd",
    front: "Stub",
    back: "Test-objekt som returnerer forhåndsdefinerte svar på kall, men sjekker ingenting. Brukes for å gi koden de inputene den trenger. Eks: stub som alltid returnerer 'true' for isLoggedIn().",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-mock",
    topic: "tdd",
    front: "Mock",
    back: "Test-objekt som ikke bare gir svar, men også VERIFISERER at det ble kalt riktig — riktige metoder, parametre, antall ganger. Brukes for å teste samhandling med samarbeidende objekter.",
    difficulty: "hard",
  },
  {
    id: "fc-tdd-simulering",
    topic: "tdd",
    front: "Simulering (test)",
    back: "En forenklet, men funksjonell implementasjon som erstatter den ekte (f.eks. in-memory database i stedet for ekte SQL). Raskere og mer forutsigbar enn ekte avhengighet.",
    difficulty: "hard",
  },
  {
    id: "fc-tdd-testpyramide",
    topic: "tdd",
    front: "Testpyramide",
    back: "Mange små enhetstester (bunnen), færre integrasjonstester, og noen få ende-til-ende-tester (toppen). Gir rask, billig tilbakemelding der det er mulig, og full systemtesting der det er nødvendig.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-equivalence",
    topic: "tdd",
    front: "Equivalence partitioning",
    back: "Test-design-teknikk: del input opp i klasser der alle verdier behandles likt, test ÉN representant fra hver klasse. Eks: alder 0-17, 18-67, 68+ — ett testtilfelle per klasse i stedet for alle verdier.",
    difficulty: "hard",
  },
  {
    id: "fc-tdd-boundary",
    topic: "tdd",
    front: "Boundary value",
    back: "Test verdiene PÅ grensene mellom equivalence-klasser — der bugs oftest ligger. Eks: 17, 18, 67, 68. Off-by-one-feil fanges her.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-alpha",
    topic: "tdd",
    front: "Alfatesting",
    back: "Intern testing utført av folk INNE I organisasjonen før produktet sendes ut. Avdekker feil i et kontrollert miljø før kunder ser produktet.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-beta",
    topic: "tdd",
    front: "Betatesting",
    back: "Testing der utvalgte EKSTERNE brukere prøver produktet i sitt eget miljø. Fanger problemer som er vanskelig å forutse internt (datasett, plattform, bruk i praksis).",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-regresjon",
    topic: "tdd",
    front: "Regresjonstesting",
    back: "Å kjøre alle (eller mange) eksisterende tester etter en endring for å sikre at funksjonalitet som FØR virket, fortsatt virker. Forutsetning for trygg refaktorering.",
    difficulty: "medium",
  },
  {
    id: "fc-tdd-fordeler",
    topic: "tdd",
    front: "Fordeler ved TDD",
    back: "Sikker testdekning fra dag én; design ledes av reelle behov; trygghet for refaktorering; testene fungerer som dokumentasjon; mindre debug-tid; bedre modularitet (testbar kode = løs kobling).",
    difficulty: "medium",
  },

  // ============================================================
  // CI-CD-DEVOPS (14)
  // ============================================================
  {
    id: "fc-ci",
    topic: "ci-cd-devops",
    front: "Continuous Integration (CI)",
    back: "Praksis der utviklere integrerer kode flere ganger daglig i felles hovedgren. Automatiserte bygg + tester kjøres ved hver push. Holder hovedgrenen alltid grønn og fanger feil tidlig.",
    difficulty: "easy",
  },
  {
    id: "fc-cd-delivery",
    topic: "ci-cd-devops",
    front: "Continuous Delivery",
    back: "Hovedgrenen er ALLTID i en tilstand som kan utgis. Hver godkjent endring genererer en utgivelsesartefakt; utgivelse til produksjon er en MANUELL beslutning men trivielt teknisk.",
    difficulty: "medium",
  },
  {
    id: "fc-cd-deployment",
    topic: "ci-cd-devops",
    front: "Continuous Deployment",
    back: "Som Continuous Delivery, men hver endring som passerer pipeline DEPLOYES automatisk til produksjon — uten manuell godkjenning. Krever svært modne tester og overvåking.",
    difficulty: "hard",
  },
  {
    id: "fc-devops",
    topic: "ci-cd-devops",
    front: "DevOps",
    back: "Kultur og praksis som bryter ned siloer mellom utvikling (Dev) og drift (Ops). Felles ansvar for hele livsløpet, automatisering, måling og tilbakemelding. CI/CD er sentralt i DevOps.",
    difficulty: "medium",
  },
  {
    id: "fc-iac",
    topic: "ci-cd-devops",
    front: "IaC",
    back: "Infrastructure as Code — infrastruktur (servere, nettverk, database) defineres i versjonskontrollerte tekstfiler (Terraform, CloudFormation). Reproduserbart, gjennomsiktig og auditerbart.",
    difficulty: "medium",
  },
  {
    id: "fc-docker",
    topic: "ci-cd-devops",
    front: "Docker",
    back: "Verktøy for å pakke applikasjon + alle avhengigheter i et lett, isolert image som kjører som en container. Sikrer at 'det virker likt overalt' — dev, test, prod.",
    difficulty: "medium",
  },
  {
    id: "fc-kubernetes",
    topic: "ci-cd-devops",
    front: "Kubernetes",
    back: "Orkestreringsplattform for containers — automatiserer deployering, skalering, lastbalansering og selvhelbredelse av containerbaserte applikasjoner. De-facto standard for produksjonsdrift av containere.",
    difficulty: "hard",
  },
  {
    id: "fc-github-actions",
    topic: "ci-cd-devops",
    front: "GitHub Actions",
    back: "GitHub sin innebygde CI/CD-tjeneste. Definer workflows i YAML i .github/workflows/. Triggere: push, PR, schedule. Kjører jobs på cloud runners. Erstatter ofte separate verktøy som Jenkins.",
    difficulty: "medium",
  },
  {
    id: "fc-blue-green",
    topic: "ci-cd-devops",
    front: "Blue/green deploy",
    back: "Deploystrategi med to identiske produksjonsmiljøer. Ny versjon deployes til 'green' mens 'blue' tar trafikken. Bytt over når green er verifisert. Rask rollback ved problemer.",
    difficulty: "hard",
  },
  {
    id: "fc-canary",
    topic: "ci-cd-devops",
    front: "Canary release",
    back: "Rull ut ny versjon til en LITEN andel brukere først (f.eks. 5 %). Overvåk metrikker; rull bredere ut hvis alt går bra, ellers rull tilbake. Reduserer eksplosjonsradius av feil.",
    difficulty: "hard",
  },
  {
    id: "fc-pipeline",
    topic: "ci-cd-devops",
    front: "CI/CD-pipeline",
    back: "Den automatiserte kjeden av steg fra commit til produksjon: hent kode → bygg → test → kvalitetssjekk → deploy til test → deploy til prod. Kodet og versjonskontrollert.",
    difficulty: "medium",
  },
  {
    id: "fc-monitoring",
    topic: "ci-cd-devops",
    front: "Monitoring/observability",
    back: "Innsamling av metrikker, logger og spor i produksjon for å oppdage og diagnostisere problemer. DevOps-praksis: 'you build it, you run it' krever at utviklere ser hva som skjer i prod.",
    difficulty: "medium",
  },
  {
    id: "fc-rollback",
    topic: "ci-cd-devops",
    front: "Rollback",
    back: "Å gå tilbake til forrige fungerende versjon når noe går galt i produksjon. Skal være raskt, automatisk og trygt. Forutsetter at deploy er reverserbar (versjonsstyrt, ingen destruktive migrations uten plan).",
    difficulty: "medium",
  },
  {
    id: "fc-feature-flag",
    topic: "ci-cd-devops",
    front: "Feature flag",
    back: "Bryter i koden som kan slå funksjonalitet av/på i prod uten ny deploy. Tillater dark launches, A/B-test, gradvis utrulling og rask 'kill switch'. Sentralt i Continuous Deployment.",
    difficulty: "hard",
  },

  // ============================================================
  // AUP (14)
  // ============================================================
  {
    id: "fc-aup-hva",
    topic: "aup",
    front: "Hva er AUP?",
    back: "Agile Unified Process — Scott Amblers forenklede versjon av RUP/UP. 4 faser × 7 disipliner. Smidigere og mer pragmatisk enn RUP, men beholder fasene og disiplinene som ramme.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-inception",
    topic: "aup",
    front: "Inception (AUP)",
    back: "Fase 1: definere visjon, omfang, økonomisk grunnlag og hovedrisikoer. Kort fase. Gir grønt lys for å gå videre i Elaboration.",
    difficulty: "easy",
  },
  {
    id: "fc-aup-elaboration",
    topic: "aup",
    front: "Elaboration (AUP)",
    back: "Fase 2: etabler arkitektur og adresser de største risikoene. Bygg en 'arkitektur-baseline' med kjørende kode — ikke bare diagrammer. Slutten = stabil arkitektur.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-construction",
    topic: "aup",
    front: "Construction (AUP)",
    back: "Fase 3: bygg ut funksjonaliteten i iterasjoner. Mest kode skrives her. Slutten = beta-klart produkt med all hovedfunksjonalitet.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-transition",
    topic: "aup",
    front: "Transition (AUP)",
    back: "Fase 4: utrulling til brukere — beta, opplæring, migrering, finjustering. Slutten = produktet er i full produksjon hos sluttbrukere.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-modellering",
    topic: "aup",
    front: "Modellering (AUP-disiplin)",
    back: "Forstå forretningen, problemområdet, og lag tilstrekkelig modeller (krav, domene, design). Kun nok modellering — ikke 'big design up front'.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-implementering",
    topic: "aup",
    front: "Implementering (AUP-disiplin)",
    back: "Skrive kode som realiserer modellen. Inkluderer enhetstester. Smidig: implementering skjer i alle faser, ikke bare i Construction.",
    difficulty: "easy",
  },
  {
    id: "fc-aup-testing",
    topic: "aup",
    front: "Testing (AUP-disiplin)",
    back: "Verifiser at systemet oppfyller krav og er av god kvalitet — enhetstester, integrasjonstester, akseptansetester. Pågår kontinuerlig.",
    difficulty: "easy",
  },
  {
    id: "fc-aup-utrulling",
    topic: "aup",
    front: "Utrulling (AUP-disiplin)",
    back: "Planlegg og utfør utrulling: pakking, installasjon, brukeropplæring, support. Hovedaktivitet i Transition-fasen, men forberedes tidligere.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-konfigstyring",
    topic: "aup",
    front: "Konfigurasjonsstyring (AUP)",
    back: "Versjonskontroll av kode og artefakter, sporing av endringer, håndtering av flere parallelle arbeidsstrømmer. Git, branch-strategi, release-tagging hører hit.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-prosjektstyring",
    topic: "aup",
    front: "Prosjektstyring (AUP)",
    back: "Lede iterasjoner, håndtere risiko, koordinere folk og rapportere fremdrift. Smidig versjon: tett samarbeid, ofte selvorganiserende team. Scrum kan dekke denne disiplinen.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-miljo",
    topic: "aup",
    front: "Miljø (AUP-disiplin)",
    back: "Sørg for at teamet har det de trenger: utviklingsverktøy, prosessbeskrivelse, infrastruktur, opplæring. 'Sett opp veibanen' så teamet kan kjøre.",
    difficulty: "medium",
  },
  {
    id: "fc-aup-7-disipliner",
    topic: "aup",
    front: "AUP — 7 disipliner",
    back: "Modellering, Implementering, Testing, Utrulling, Konfigurasjonsstyring, Prosjektstyring, Miljø. Hver disiplin har varierende intensitet gjennom de 4 fasene.",
    difficulty: "hard",
  },
  {
    id: "fc-aup-scrum",
    topic: "aup",
    front: "AUP + Scrum",
    back: "AUP gir den overordnede livsløpsrammen (faser + disipliner); Scrum brukes som styringsrammeverk i Construction (sprinter, roller, seremonier). De utfyller hverandre — Scrum sier ingenting om livssyklus.",
    difficulty: "hard",
  },

  // ============================================================
  // KANBAN (10)
  // ============================================================
  {
    id: "fc-kanban-hva",
    topic: "kanban",
    front: "Hva er Kanban?",
    back: "Smidig metode med opprinnelse i Toyota Production System. Visualiserer arbeidsflyt på en tavle, begrenser pågående arbeid (WIP) og styrer flyten i stedet for tidsbokser.",
    difficulty: "easy",
  },
  {
    id: "fc-kanban-tavle",
    topic: "kanban",
    front: "Kanban-tavle",
    back: "Visuell tavle med kolonner som representerer steg i arbeidsflyten (f.eks. Backlog, Pågår, Review, Ferdig). Hver oppgave er et kort som flyttes mellom kolonnene.",
    difficulty: "easy",
  },
  {
    id: "fc-kanban-wip",
    topic: "kanban",
    front: "WIP-limit",
    back: "Work In Progress-limit — maks antall oppgaver tillatt i en kolonne samtidig. Tvinger fram fokus, avdekker flaskehalser og reduserer kontekstbytte. Den viktigste mekanismen i Kanban.",
    difficulty: "medium",
  },
  {
    id: "fc-kanban-pull-vs-push",
    topic: "kanban",
    front: "Pull vs push",
    back: "Push: arbeid dyttes inn i neste steg uavhengig av kapasitet (kø bygger seg opp). Pull (Kanban): et steg HENTER inn nytt arbeid bare når det har ledig kapasitet (WIP-limit ikke nådd).",
    difficulty: "medium",
  },
  {
    id: "fc-kanban-cfd",
    topic: "kanban",
    front: "Cumulative Flow Diagram",
    back: "Diagram som viser antall oppgaver i hver kolonne over tid (stablede områder). Brede områder = flaskehals; jevne, parallelle linjer = sunn flyt. Brukes til å diagnostisere prosessen.",
    difficulty: "hard",
  },
  {
    id: "fc-kanban-scrumban",
    topic: "kanban",
    front: "Scrumban",
    back: "Hybrid av Scrum og Kanban — typisk Scrum-roller og -seremonier kombinert med Kanban sin tavle, WIP-limits og pull-styring. Brukes ofte ved overgang fra Scrum til Kanban.",
    difficulty: "hard",
  },
  {
    id: "fc-kanban-lead-time",
    topic: "kanban",
    front: "Lead time",
    back: "Tid fra en oppgave kommer på backloggen til den er ferdig levert. Måles statistisk, brukes for å forutsi leveranseevne og oppdage forbedringer.",
    difficulty: "medium",
  },
  {
    id: "fc-kanban-cycle-time",
    topic: "kanban",
    front: "Cycle time",
    back: "Tid fra arbeid begynner på en oppgave til den er ferdig. Kortere cycle time = raskere flyt. Lavere WIP-limits gir typisk kortere cycle time (Little's law).",
    difficulty: "hard",
  },
  {
    id: "fc-kanban-throughput",
    topic: "kanban",
    front: "Throughput",
    back: "Antall oppgaver fullført per tidsenhet (f.eks. per uke). Måler teamets faktiske leveransekapasitet og brukes til prognoser.",
    difficulty: "medium",
  },
  {
    id: "fc-kanban-vs-scrum",
    topic: "kanban",
    front: "Kanban vs Scrum",
    back: "Scrum: tidsbokser (sprinter), faste roller, sprintforpliktelse. Kanban: kontinuerlig flyt, ingen faste roller eller sprinter, WIP-styring. Kanban tåler bedre uforutsigbart innkommende arbeid (support, drift).",
    difficulty: "hard",
  },

  // ============================================================
  // ARKITEKTUR (16)
  // ============================================================
  {
    id: "fc-ark-arkitektur",
    topic: "arkitektur",
    front: "Programvarearkitektur",
    back: "De grunnleggende strukturene i et system: komponenter, deres relasjoner og prinsippene for design og evolusjon. Beslutninger tatt tidlig som er kostbare å reversere senere (Sommerville kap 4).",
    difficulty: "medium",
  },
  {
    id: "fc-ark-responsiveness",
    topic: "arkitektur",
    front: "Responsiveness",
    back: "Kvalitetsattributt: hvor raskt systemet svarer brukeren. Tett knyttet til UX. Påvirkes av algoritmer, caching, lasting i bakgrunn, asynkrone kall.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-reliability",
    topic: "arkitektur",
    front: "Reliability",
    back: "Pålitelighet — sannsynligheten for at systemet leverer riktig svar over en gitt tidsperiode. Måles f.eks. som mean time between failures (MTBF).",
    difficulty: "medium",
  },
  {
    id: "fc-ark-availability",
    topic: "arkitektur",
    front: "Availability",
    back: "Tilgjengelighet — andelen tid systemet er oppe og brukbart. Måles som '99,9 %' (three nines = ca. 8,76 timer nede per år). Krever redundans, failover, overvåking.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-security",
    topic: "arkitektur",
    front: "Security",
    back: "Sikkerhet: beskyttelse mot uautorisert tilgang og angrep. Innebærer autentisering, autorisasjon, kryptering, validering, audit. Må arkitekturalt forankres — ikke 'bolt on'.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-usability",
    topic: "arkitektur",
    front: "Usability",
    back: "Brukervennlighet — hvor lett systemet er å lære og bruke. Påvirkes av UI-design, feilhåndtering, hjelpetekster, tilgjengelighet (a11y) og responstid.",
    difficulty: "easy",
  },
  {
    id: "fc-ark-maintainability",
    topic: "arkitektur",
    front: "Maintainability",
    back: "Vedlikeholdbarhet — hvor lett systemet er å endre, fikse og utvide etter at det er i drift. Påvirkes av modularitet, kodekvalitet, dokumentasjon og testdekning.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-resilience",
    topic: "arkitektur",
    front: "Resilience",
    back: "Robusthet — evnen til å håndtere feil og fortsette å levere (kanskje redusert) tjeneste. Inkluderer retries, fallback, sirkulærbrytere, isolering. Antar at feil VIL skje.",
    difficulty: "hard",
  },
  {
    id: "fc-ark-layered",
    topic: "arkitektur",
    front: "Lagdelt arkitektur",
    back: "Systemet deles i lag (f.eks. presentasjon, forretningslogikk, datatilgang) der hvert lag bare snakker med laget direkte under. Gir separation of concerns og lett utskifting av lag.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-mvc",
    topic: "arkitektur",
    front: "MVC",
    back: "Model-View-Controller: Model = data og forretningsregler; View = UI-presentasjon; Controller = håndterer input og oppdaterer Model/View. Skiller UI fra logikk; støtter flere views på samme model.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-multi-tier",
    topic: "arkitektur",
    front: "Multi-tier (n-tier)",
    back: "Lagdeling distribuert over flere fysiske/logiske noder — typisk klient (presentasjon) → applikasjonsserver → database. Tre-lags er klassisk webarkitektur.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-microservices",
    topic: "arkitektur",
    front: "Microservices",
    back: "Arkitektur der systemet bygges som mange små, uavhengige tjenester som kommuniserer over nettverk (HTTP/queue). Hver tjeneste eier sin data og kan deployes uavhengig. Skalerer team og funksjoner — men øker driftskompleksitet.",
    difficulty: "hard",
  },
  {
    id: "fc-ark-sql",
    topic: "arkitektur",
    front: "SQL-database",
    back: "Relasjonsdatabase (Postgres, MySQL, Oracle) med strikt skjema, ACID-transaksjoner og SQL som spørringsspråk. Egnet når data er strukturert og konsistens er kritisk.",
    difficulty: "easy",
  },
  {
    id: "fc-ark-nosql",
    topic: "arkitektur",
    front: "NoSQL-database",
    back: "Ikke-relasjonelle databaser (dokument, kolonne, graf, key-value). Skjemafrihet og horisontal skalering. Egnet når data er ustrukturert/halvstrukturert eller når skalering trumfer streng konsistens.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-soc",
    topic: "arkitektur",
    front: "Separation of concerns",
    back: "Designprinsipp: hvert modul/lag har ÉT velavgrenset ansvar. Reduserer kompleksitet, øker gjenbruk og letter testing. Realiseres i lagdeling, MVC, microservices osv.",
    difficulty: "medium",
  },
  {
    id: "fc-ark-stable-interfaces",
    topic: "arkitektur",
    front: "Stable interfaces",
    back: "Grensesnittene mellom moduler/tjenester skal være stabile selv om implementasjonen endres. Beskytter klienter mot endringer (versjonering, bakoverkompatibilitet). Tett knyttet til Protected Variations (GRASP).",
    difficulty: "hard",
  },

  // ============================================================
  // OOP-JAVA (14)
  // ============================================================
  {
    id: "fc-java-public",
    topic: "oop-java",
    front: "+ → Java",
    back: "UML-synlighet '+' (public) mappes til 'public' i Java. Eks: public String getNavn() { ... }. Synlig for alle klasser overalt.",
    difficulty: "easy",
  },
  {
    id: "fc-java-private",
    topic: "oop-java",
    front: "- → Java",
    back: "UML-synlighet '-' (private) mappes til 'private' i Java. Eks: private int alder; Bare tilgjengelig i samme klasse. Hovedmekanismen for innkapsling.",
    difficulty: "easy",
  },
  {
    id: "fc-java-protected",
    topic: "oop-java",
    front: "# → Java",
    back: "UML-synlighet '#' (protected) mappes til 'protected' i Java. Tilgjengelig i samme klasse, samme pakke OG i subklasser (selv i andre pakker).",
    difficulty: "medium",
  },
  {
    id: "fc-java-package",
    topic: "oop-java",
    front: "~ → Java",
    back: "UML-synlighet '~' (package) mappes til Java sin standardsynlighet — INGEN modifikator. Eks: int alder; Tilgjengelig fra klasser i samme pakke, ikke utenfor.",
    difficulty: "medium",
  },
  {
    id: "fc-java-interface-vs-abstract",
    topic: "oop-java",
    front: "Interface vs abstrakt klasse",
    back: "Interface: ren kontrakt, ingen tilstand (felter), klasse kan implementere mange. Abstrakt klasse: kan ha felter og delvis implementasjon, klasse kan utvide bare én. Interface foretrekkes for løs kobling.",
    difficulty: "hard",
  },
  {
    id: "fc-java-enum",
    topic: "oop-java",
    front: "enum (Java)",
    back: "Type med fast antall navngitte instanser. Eks: enum Farge { RØD, GRØNN, BLÅ }. Brukes for tilstander, kategorier, valg. Tryggere og mer lesbart enn int-konstanter.",
    difficulty: "medium",
  },
  {
    id: "fc-java-equals",
    topic: "oop-java",
    front: "equals()",
    back: "Metoden for å sammenligne to objekters INNHOLD (logisk likhet), i motsetning til '==' som sammenligner referanser. Må overstyres når man definerer 'innholdslikhet'. Skal være refleksiv, symmetrisk, transitiv.",
    difficulty: "medium",
  },
  {
    id: "fc-java-hashcode",
    topic: "oop-java",
    front: "hashCode()",
    back: "Returnerer en int som brukes av hashbaserte samlinger (HashMap, HashSet). Kontrakt: hvis a.equals(b), så MÅ a.hashCode() == b.hashCode(). Overstyr ALLTID sammen med equals().",
    difficulty: "hard",
  },
  {
    id: "fc-java-multiplicitet-1",
    topic: "oop-java",
    front: "Multiplisitet 1 → Java",
    back: "En til-en-relasjon: feltet er en enkel referanse. Eks: private Adresse adresse; Initialisert i konstruktør eller via setter, ikke samling.",
    difficulty: "easy",
  },
  {
    id: "fc-java-multiplicitet-mange",
    topic: "oop-java",
    front: "Multiplisitet * → Java",
    back: "En-til-mange-relasjon: feltet er en samling. Eks: private List<Bestilling> bestillinger = new ArrayList<>(); Initialiser ved deklarasjon for å unngå NullPointerException.",
    difficulty: "medium",
  },
  {
    id: "fc-java-override",
    topic: "oop-java",
    front: "@Override",
    back: "Annotation som markerer at metoden overstyrer en metode i superklasse/interface. Kompilatoren feiler hvis signaturen ikke matcher — fanger skrivefeil. Bør alltid brukes ved overstyring.",
    difficulty: "medium",
  },
  {
    id: "fc-java-javadoc",
    topic: "oop-java",
    front: "JavaDoc",
    back: "Standardisert dokumentasjon i kommentarer /** ... */ over klasser/metoder. Tags: @param, @return, @throws. Genererer HTML-dokumentasjon. Brukes for å beskrive kontrakter (HVA, ikke HVORDAN).",
    difficulty: "easy",
  },
  {
    id: "fc-java-konstruktor",
    topic: "oop-java",
    front: "Konstruktør",
    back: "Spesiell metode med samme navn som klassen og uten returtype. Kjøres når 'new Klasse(...)' kalles. Initialiserer feltene. Java gir en default no-args konstruktør hvis ingen er definert.",
    difficulty: "easy",
  },
  {
    id: "fc-java-final",
    topic: "oop-java",
    front: "final (Java)",
    back: "På felt: kan kun settes én gang (konstant). På metode: kan ikke overstyres. På klasse: kan ikke arves. Brukes for å sikre uforanderlighet og forhindre uønsket utvidelse.",
    difficulty: "medium",
  },
];
