// Type-safe accessors for DAT110 vault data.
// JSON is generated by scripts/sync-dat110-vault.mjs and lives in src/data/dat110-vault/.

import conceptsData from "@/data/dat110-vault/concepts-tier1.json";
import topicsData from "@/data/dat110-vault/topics-tier1.json";
import wikilinkIndex from "@/data/dat110-vault/_wikilink-index.json";
import metaData from "@/data/dat110-vault/_meta.json";
import type {
  DAT110Concept,
  DAT110Topic,
  DAT110VaultMeta,
} from "./types";

const concepts = (conceptsData as { concepts: DAT110Concept[] }).concepts;
const topics = (topicsData as { topics: DAT110Topic[] }).topics;
const routes = (wikilinkIndex as { routes: Record<string, string> }).routes;
const meta = metaData as DAT110VaultMeta;

export function getAllConceptSlugs(): string[] {
  return concepts.map((c) => c.slug);
}

export function getAllTopicSlugs(): string[] {
  return topics.map((t) => t.slug);
}

export function getConceptBySlug(slug: string): DAT110Concept | null {
  return concepts.find((c) => c.slug === slug) ?? null;
}

export function getTopicBySlug(slug: string): DAT110Topic | null {
  return topics.find((t) => t.slug === slug) ?? null;
}

export function getMeta(): DAT110VaultMeta {
  return meta;
}

export function resolveWikilinkRoute(target: string): string | null {
  return routes[target] ?? null;
}
